import {describe,expect,it,vi} from 'vitest'
import {createHttpCostWorkflowRepository} from '../../../app/repositories/http/http-cost-workflow-repository'
import {createAuthenticatedHttpClient} from '../../../app/repositories/http/authenticated-http-client'
const id='c1f50000-0000-4000-8000-000000000001'
const other='c1f50000-0000-4000-8000-000000000002'
const command={idempotencyKey:id}
const response=(data:unknown)=>({request:vi.fn(async({schema}:{schema:{parse(v:unknown):unknown}})=>schema.parse(data))})
describe('typed cost workflow HTTP contract',()=>{
 it('captures the active company exactly once per scoped request, never the prototype fallback',async()=>{const companyId=vi.fn().mockReturnValue(id),client=response([]);const r=createHttpCostWorkflowRepository({companyId,client:client as never});await r.listRequests(id);expect(companyId).toHaveBeenCalledOnce();expect(client.request).toHaveBeenCalledWith(expect.objectContaining({url:'/api/companies/'+id+'/projects/'+id+'/cost-workflow/requests',method:'GET'}));companyId.mockReturnValue(other);await r.listRequests(id);expect(client.request.mock.calls[1]?.[0]).toMatchObject({url:'/api/companies/'+other+'/projects/'+id+'/cost-workflow/requests'})})
 it('does not issue network requests without a current company or valid scope',async()=>{const client=response([]),r=createHttpCostWorkflowRepository({companyId:()=>null,client:client as never});await expect(r.listRequests(id)).rejects.toThrow('ACTIVE_COMPANY_REQUIRED');expect(client.request).not.toHaveBeenCalled();const valid=createHttpCostWorkflowRepository({companyId:id,client:client as never});await expect(valid.listRequests('../other-project')).rejects.toThrow();expect(client.request).not.toHaveBeenCalled()})
 it('preserves idempotency and target revision across a lost-response retry',async()=>{const client=response({paymentId:id,version:1,replayed:true}),r=createHttpCostWorkflowRepository({companyId:id,client:client as never});const input={amount:'10',currencyCode:'VND',paymentDate:'2026-10-05',reference:'Synthetic transfer',evidenceFileIds:[id],expectedVersion:0};await r.confirmPayment(id,id,input,command);await r.confirmPayment(id,id,input,command);expect(client.request.mock.calls.map(c=>c[0])).toEqual([expect.objectContaining({method:'POST',idempotencyKey:id,body:input,url:'/api/companies/'+id+'/projects/'+id+'/cost-workflow/installments/'+id+'/payments'}),expect.objectContaining({idempotencyKey:id,body:input})])})
 it('cannot call legacy financial writers or accept browser actor/capacity flags',async()=>{const client=response({version:1,replayed:false}),r=createHttpCostWorkflowRepository({companyId:id,client:client as never});const input={amount:'10',currencyCode:'VND',paymentDate:'2026-10-05',reference:'Synthetic transfer',evidenceFileIds:[id],expectedVersion:0,actorId:id};await expect(r.confirmPayment(id,id,input as never,command)).rejects.toThrow();expect(client.request).not.toHaveBeenCalled()})
 it('uses actual existing manager PUT and reviewed original read-url POST URLs',async()=>{const client=response({assignmentId:id,version:1,replayed:false}),r=createHttpCostWorkflowRepository({companyId:id,client:client as never});await r.assignManager(id,{managerUserId:id,expectedAssignmentVersion:0,reason:'Synthetic handover'},command);expect(client.request).toHaveBeenCalledWith(expect.objectContaining({url:'/api/companies/'+id+'/projects/'+id+'/cost-workflow/manager',method:'PUT',idempotencyKey:id}));const signed=response({url:'https://example.invalid/synthetic',expiresAt:'2026-10-05T00:01:00Z'});await createHttpCostWorkflowRepository({companyId:id,client:signed as never}).readEvidenceUrl(id,id,{disposition:'attachment'});expect(signed.request).toHaveBeenCalledWith(expect.objectContaining({url:'/api/companies/'+id+'/projects/'+id+'/cost-workflow/evidence/'+id+'/read-url',method:'POST',body:{disposition:'attachment'}}))})
 it('retains backend conflict codes through the authenticated client',async()=>{const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{code:'VERSION_CONFLICT',message:'Synthetic version conflict',requestId:id,details:{}}}),{status:409,headers:{'Content-Type':'application/json'}}));const client=createAuthenticatedHttpClient({getAccessToken:()=> 'synthetic-session-token',fetch});const r=createHttpCostWorkflowRepository({companyId:id,client});await expect(r.submitRequest(id,id,{expectedVersion:1},command)).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(fetch.mock.calls[0]?.[1]?.headers).toMatchObject({'Idempotency-Key':id})})
})
