begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(80);
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_companies'::regclass),'cost_workflow_companies forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_companies','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_companies has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_companies','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_companies has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_companies','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_companies requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_companies'::regclass and not tgisinternal and tgname='cost_workflow_companies_retain'),'cost_workflow_companies retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_party_classifications'::regclass),'cost_workflow_party_classifications forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_party_classifications','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_party_classifications has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_party_classifications','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_party_classifications has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_party_classifications','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_party_classifications requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_party_classifications'::regclass and not tgisinternal and tgname='cost_workflow_party_classifications_retain'),'cost_workflow_party_classifications retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_manager_assignments'::regclass),'cost_workflow_manager_assignments forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_manager_assignments','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_manager_assignments has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_manager_assignments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_manager_assignments has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_manager_assignments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_manager_assignments requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_manager_assignments'::regclass and not tgisinternal and tgname='cost_workflow_manager_assignments_retain'),'cost_workflow_manager_assignments retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_contracts'::regclass),'cost_workflow_contracts forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_contracts','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contracts has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_contracts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contracts has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_contracts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contracts requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_contracts'::regclass and not tgisinternal and tgname='cost_workflow_contracts_retain'),'cost_workflow_contracts retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_contract_versions'::regclass),'cost_workflow_contract_versions forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_contract_versions','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contract_versions has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_contract_versions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contract_versions has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_contract_versions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_contract_versions requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_contract_versions'::regclass and not tgisinternal and tgname='cost_workflow_contract_versions_retain'),'cost_workflow_contract_versions retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_requests'::regclass),'cost_workflow_requests forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_requests','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_requests has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_requests','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_requests has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_requests','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_requests requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_requests'::regclass and not tgisinternal and tgname='cost_workflow_requests_retain'),'cost_workflow_requests retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_request_versions'::regclass),'cost_workflow_request_versions forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_request_versions','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_request_versions has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_request_versions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_request_versions has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_request_versions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_request_versions requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_request_versions'::regclass and not tgisinternal and tgname='cost_workflow_request_versions_retain'),'cost_workflow_request_versions retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_decisions'::regclass),'cost_workflow_decisions forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_decisions','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_decisions has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_decisions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_decisions has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_decisions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_decisions requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_decisions'::regclass and not tgisinternal and tgname='cost_workflow_decisions_retain'),'cost_workflow_decisions retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_installments'::regclass),'cost_workflow_installments forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_installments','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_installments has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_installments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_installments has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_installments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_installments requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_installments'::regclass and not tgisinternal and tgname='cost_workflow_installments_retain'),'cost_workflow_installments retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_payments'::regclass),'cost_workflow_payments forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_payments','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_payments has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_payments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_payments has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_payments','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_payments requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_payments'::regclass and not tgisinternal and tgname='cost_workflow_payments_retain'),'cost_workflow_payments retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_consumptions'::regclass),'cost_workflow_consumptions forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_consumptions','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_consumptions has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_consumptions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_consumptions has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_consumptions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_consumptions requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_consumptions'::regclass and not tgisinternal and tgname='cost_workflow_consumptions_retain'),'cost_workflow_consumptions retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_refunds'::regclass),'cost_workflow_refunds forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_refunds','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_refunds has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_refunds','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_refunds has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_refunds','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_refunds requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_refunds'::regclass and not tgisinternal and tgname='cost_workflow_refunds_retain'),'cost_workflow_refunds retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_corrections'::regclass),'cost_workflow_corrections forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_corrections','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_corrections has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_corrections','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_corrections has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_corrections','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_corrections requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_corrections'::regclass and not tgisinternal and tgname='cost_workflow_corrections_retain'),'cost_workflow_corrections retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_notifications'::regclass),'cost_workflow_notifications forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_notifications','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_notifications has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_notifications','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_notifications has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_notifications','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_notifications requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_notifications'::regclass and not tgisinternal and tgname='cost_workflow_notifications_retain'),'cost_workflow_notifications retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_extractions'::regclass),'cost_workflow_extractions forces RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_extractions','INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_extractions has no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_extractions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_extractions has no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_extractions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cost_workflow_extractions requires reviewed commands even for service role');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_extractions'::regclass and not tgisinternal and tgname='cost_workflow_extractions_retain'),'cost_workflow_extractions retains history');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.cost_workflow_cash_proof_claims'::regclass),'cash proof claims force RLS');
select ok(not has_table_privilege('authenticated','public.cost_workflow_cash_proof_claims','INSERT,UPDATE,DELETE,TRUNCATE'),'cash proof claims have no direct authenticated DML');
select ok(not has_table_privilege('anon','public.cost_workflow_cash_proof_claims','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cash proof claims have no anonymous privileges');
select ok(not has_table_privilege('service_role','public.cost_workflow_cash_proof_claims','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'cash proof claims require reviewed commands');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cost_workflow_cash_proof_claims'::regclass and not tgisinternal and tgname='c1_workflow_cash_proof_claims_retain'),'cash proof claims retain history');
select * from finish();
rollback;
