import { z } from 'zod'
import { accountingSourceSchema, accountingSourceVersionSchema, sourceReportedFigureSchema, sourceSelectionSchema } from '../../../shared/schemas/costs/sources'
import { AppApiError } from '../../utils/api-error'
import type { UserSupabaseClient } from '../../utils/supabase-client'

interface Query { select(columns: string): Query; eq(column: string, value: string): Query; order(column: string): PromiseLike<{ data: unknown; error: unknown }>; maybeSingle(): Promise<{ data: unknown; error: unknown }> }
interface Client { from(table: 'accounting_sources' | 'accounting_source_versions' | 'source_reported_figures' | 'source_review_issues'): Query; rpc(name: string, args: Record<string, unknown>): Promise<{ data: unknown; error: unknown }> }
function fail(): never { throw new AppApiError(500, 'INTERNAL_ERROR', 'Không thể xử lý nguồn kế toán.') }
function result<T>(schema: z.ZodType<T>, value: unknown, error: unknown): T { if (error) return fail(); const parsed = schema.safeParse(value); if (!parsed.success) return fail(); return parsed.data }
function source(value: unknown) { const row = z.object({ id: z.string().uuid(), code: z.string(), title: z.string(), source_system: z.string(), suggested_project_id: z.string().uuid().nullable(), is_archived: z.boolean(), version: z.number(), created_at: z.string().datetime(), updated_at: z.string().datetime() }).safeParse(value); if (!row.success) return fail(); return accountingSourceSchema.parse({ id: row.data.id, code: row.data.code, title: row.data.title, sourceSystem: row.data.source_system, suggestedProjectId: row.data.suggested_project_id, isArchived: row.data.is_archived, version: row.data.version, createdAt: row.data.created_at, updatedAt: row.data.updated_at }) }
export function createSupabaseAccountingSourceRepository(db: UserSupabaseClient) {
  const client = db as unknown as Client
  return {
    async listSources(input: Record<string, unknown>) { const { data, error } = await client.from('accounting_sources').select('*').eq('tenant_id', String(input.tenantId)).eq('company_id', String(input.companyId)).order('created_at'); if (error || !Array.isArray(data)) return fail(); return data.map(source) },
    async getSource(input: Record<string, unknown>) { const { data, error } = await client.from('accounting_sources').select('*').eq('tenant_id', String(input.tenantId)).eq('company_id', String(input.companyId)).eq('id', String(input.sourceId)).maybeSingle(); if (error) return fail(); return data ? source(data) : null },
    async createSource(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_accounting_source', { target_company_id: input.companyId, target_input: input, target_request_id: input.requestId }); return result(accountingSourceSchema, data, error) },
    async updateSource(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_update_accounting_source', { target_company_id: input.companyId, target_id: input.sourceId, target_input: input, target_request_id: input.requestId }); return result(accountingSourceSchema, data, error) },
    async createVersion(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_accounting_source_version', { target_company_id: input.companyId, target_source_id: input.sourceId, target_input: input, target_request_id: input.requestId }); return result(z.object({ id: z.string().uuid(), status: z.enum(['draft', 'shared']), file: z.object({ state: z.enum(['pending', 'ready', 'rejected', 'abandoned']) }) }), data, error) },
    async getVersion(input: Record<string, unknown>) { const { data, error } = await client.from('accounting_source_versions').select('*').eq('tenant_id', String(input.tenantId)).eq('company_id', String(input.companyId)).eq('id', String(input.versionId)).maybeSingle(); if (error || !data) return fail(); const parsed = accountingSourceVersionSchema.safeParse(data); if (!parsed.success) return fail(); return { ...parsed.data, file: { state: (data as { file_state?: string }).file_state ?? 'pending' } } },
    async shareVersion(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_share_accounting_source_version', { target_company_id: input.companyId, target_id: input.versionId, target_input: input, target_request_id: input.requestId }); return result(accountingSourceVersionSchema, data, error) },
    async createSelection(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_source_selection', { target_company_id: input.companyId, target_source_version_id: input.sourceVersionId, target_input: input, target_request_id: input.requestId }); return result(sourceSelectionSchema, data, error) },
    async createFigure(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_source_reported_figure', { target_company_id: input.companyId, target_source_selection_id: input.selectionId, target_input: input, target_request_id: input.requestId }); return result(sourceReportedFigureSchema, data, error) },
    async getFigure(input: Record<string, unknown>) { const { data, error } = await client.from('source_reported_figures').select('*').eq('tenant_id', String(input.tenantId)).eq('company_id', String(input.companyId)).eq('id', String(input.figureId)).maybeSingle(); if (error || !data) return fail(); const figure = sourceReportedFigureSchema.safeParse(data); if (!figure.success) return fail(); return { ...figure.data, sourceVersionStatus: (data as { source_version_status?: string }).source_version_status ?? 'draft' } },
    async shareFigure(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_share_source_reported_figure', { target_company_id: input.companyId, target_id: input.figureId, target_input: input, target_request_id: input.requestId }); return result(sourceReportedFigureSchema, data, error) },
    async updateFigure(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_update_source_reported_figure', { target_company_id: input.companyId, target_id: input.figureId, target_input: input, target_request_id: input.requestId }); return result(sourceReportedFigureSchema, data, error) },
    async createRevision(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_source_figure_revision', { target_company_id: input.companyId, target_id: input.figureId, target_input: input, target_request_id: input.requestId }); return result(sourceReportedFigureSchema, data, error) },
    async createIssue(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_create_source_review_issue', { target_company_id: input.companyId, target_source_selection_id: input.selectionId, target_input: input, target_request_id: input.requestId }); if (error) return fail(); return data },
    async getIssue(input: Record<string, unknown>) { const { data, error } = await client.from('source_review_issues').select('status').eq('tenant_id', String(input.tenantId)).eq('company_id', String(input.companyId)).eq('id', String(input.issueId)).maybeSingle(); if (error) return fail(); return data as { status: string } | null },
    async resolveIssue(input: Record<string, unknown>) { const { data, error } = await client.rpc('c1_resolve_source_review_issue', { target_company_id: input.companyId, target_id: input.issueId, target_input: input, target_request_id: input.requestId }); if (error) return fail(); return data },
  }
}
