import type { PermissionCode } from '../../../shared/constants/permissions'
import { createAccountingSourceInputSchema, createAccountingSourceVersionInputSchema, createSourceFigureInputSchema, createSourceFigureRevisionInputSchema, createSourceSelectionInputSchema, idempotencyInputSchema, updateAccountingSourceInputSchema, updateSourceFigureInputSchema } from '../../../shared/schemas/costs/sources'
import { AppApiError } from '../../utils/api-error'

type Context = { actorId: string; tenantId: string; companyId: string; permissions: readonly PermissionCode[]; requestId: string }
type Repository = Record<string, (input: Record<string, unknown>) => Promise<Record<string, unknown>>>
function fail(status: number, code: 'PERMISSION_DENIED' | 'SOURCE_FILE_NOT_READY' | 'SOURCE_SELECTION_SCOPE_MISMATCH' | 'SOURCE_FIGURE_IMMUTABLE' | 'RESOURCE_NOT_FOUND', message: string): never { throw new AppApiError(status, code, message) }
function requirePrepare(context: Context) { if (!context.permissions.includes('cost.source.read') || !context.permissions.includes('cost.prepare')) fail(403, 'PERMISSION_DENIED', 'Bạn không có quyền chuẩn bị nguồn.') }
function requireSourceRead(context: Context) { if (!context.permissions.includes('cost.source.read')) fail(403, 'PERMISSION_DENIED', 'Bạn không có quyền đọc nguồn.') }
function requirePublish(context: Context) { requirePrepare(context); if (!context.permissions.includes('cost.publish_import')) fail(403, 'PERMISSION_DENIED', 'Bạn không có quyền chia sẻ nguồn.') }
function cell(value: string) { const parsed = /^([A-Za-z]+)(\d+)$/.exec(value.trim()); if (!parsed) throw new Error('invalid A1 range'); let column = 0; for (const character of parsed[1]!.toUpperCase()) column = column * 26 + character.charCodeAt(0) - 64; return { column, row: Number(parsed[2]), text: `${parsed[1]!.toUpperCase()}${Number(parsed[2])}` } }
export function normalizeSourceLocator(locator: { kind: string; sheetName?: string; range?: string; fromPage?: number; toPage?: number; note?: string }) {
  if (locator.kind === 'whole_file') return { kind: 'whole_file', ...(locator.note ? { note: locator.note } : {}), locatorKey: `whole_file|${locator.note ?? ''}` }
  if (locator.kind === 'page_range') return { kind: 'page_range', fromPage: locator.fromPage!, toPage: locator.toPage!, locatorKey: `page_range|${locator.fromPage}-${locator.toPage}` }
  const [left, right] = locator.range!.split(':'); const a = cell(left!); const b = cell(right ?? left!); const start = a.row < b.row || a.row === b.row && a.column <= b.column ? a : b; const end = start === a ? b : a; const range = `${start.text}:${end.text}`
  return { kind: 'cell_range', sheetName: locator.sheetName!, range, locatorKey: `cell_range|${locator.sheetName}|${range}` }
}
export function createAccountingSourceService(repository: Repository) {
  return {
    async list(context: Context) { requireSourceRead(context); return repository.listSources!({ tenantId: context.tenantId, companyId: context.companyId, includeDraft: context.permissions.includes('cost.prepare') }) },
    async get(context: Context, sourceId: string) { requireSourceRead(context); const source = await repository.getSource!({ sourceId, tenantId: context.tenantId, companyId: context.companyId }); return source ?? fail(404, 'RESOURCE_NOT_FOUND', 'Không tìm thấy nguồn kế toán.') },
    async createSource(context: Context, input: unknown) { requirePrepare(context); return repository.createSource!({ ...createAccountingSourceInputSchema.parse(input), tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, requestId: context.requestId }) },
    async updateSource(context: Context, sourceId: string, input: unknown) { requirePrepare(context); return repository.updateSource!({ ...updateAccountingSourceInputSchema.parse(input), sourceId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, requestId: context.requestId }) },
    async createVersion(context: Context, sourceId: string, input: unknown) { requirePrepare(context); return repository.createVersion!({ ...createAccountingSourceVersionInputSchema.parse(input), sourceId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, requestId: context.requestId, projectId: undefined, engagementId: undefined }) },
    async shareVersion(context: Context, versionId: string, input: unknown) { requirePublish(context); const version = await repository.getVersion!({ versionId, tenantId: context.tenantId, companyId: context.companyId }); if (version.status !== 'draft' || (version.file as { state?: string } | undefined)?.state !== 'ready') fail(409, 'SOURCE_FILE_NOT_READY', 'File nguồn chưa sẵn sàng để chia sẻ.'); return { ...await repository.shareVersion!({ versionId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, ...idempotencyInputSchema.parse(input) }), financialActivation: false } },
    async createSelection(context: Context, sourceVersionId: string, input: unknown) { requirePrepare(context); const value = createSourceSelectionInputSchema.parse(input); if (value.handling === 'ready_for_normalization' && (value.sourceRole === 'unknown' || !value.mappedProjectId || !value.mappedEngagementId)) fail(409, 'SOURCE_SELECTION_SCOPE_MISMATCH', 'Selection chưa có phạm vi hoặc bản chất rõ ràng.'); return { ...await repository.createSelection!({ ...value, ...normalizeSourceLocator(value.locator), sourceVersionId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId }), financialActivation: false } },
    async createFigure(context: Context, selectionId: string, input: unknown) { requirePrepare(context); return { ...await repository.createFigure!({ ...createSourceFigureInputSchema.parse(input), selectionId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, requestId: context.requestId, financialActivation: false }), financialActivation: false } },
    async shareFigure(context: Context, figureId: string, input: unknown) { requirePublish(context); const figure = await repository.getFigure!({ figureId, tenantId: context.tenantId, companyId: context.companyId }); if (figure.status !== 'draft' && figure.status !== 'shared' || figure.sourceVersionStatus !== 'shared') fail(409, 'SOURCE_FILE_NOT_READY', 'Source figure chưa thể chia sẻ.'); return { ...await repository.shareFigure!({ figureId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, ...idempotencyInputSchema.parse(input) }), financialActivation: false } },
    async updateFigure(context: Context, figureId: string, input: unknown) { requirePrepare(context); const figure = await repository.getFigure!({ figureId, tenantId: context.tenantId, companyId: context.companyId }); if (figure.status === 'shared') fail(409, 'SOURCE_FIGURE_IMMUTABLE', 'Source figure đã chia sẻ phải tạo revision.'); return repository.updateFigure!({ figureId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, ...updateSourceFigureInputSchema.parse(input) }) },
    async createFigureRevision(context: Context, figureId: string, input: unknown) { requirePrepare(context); const figure = await repository.getFigure!({ figureId, tenantId: context.tenantId, companyId: context.companyId }); if (figure.status !== 'shared') fail(409, 'RESOURCE_NOT_FOUND', 'Chỉ source figure đã chia sẻ mới có revision.'); return repository.createRevision!({ figureId, figureFamilyId: figure.figureFamilyId, replacesFigureId: figureId, tenantId: context.tenantId, companyId: context.companyId, actorId: context.actorId, ...createSourceFigureRevisionInputSchema.parse(input) }) },
  }
}
