import { z } from 'zod'
import { companyCostSettingsSchema, type CompanyCostSettings } from '../../../shared/schemas/costs/master-data'
import { AppApiError } from '../../utils/api-error'
import type { UserSupabaseClient } from '../../utils/supabase-client'
const row = z.object({ company_id: z.string().uuid(), tenant_id: z.string().uuid(), enabled: z.boolean(), default_currency_code: z.string().length(3), money_scale: z.number().int().min(0).max(4), time_zone: z.string().min(1), version: z.number().int().nonnegative(), created_at: z.string().datetime(), updated_at: z.string().datetime() }).strict()
interface Query { select(columns: string): Query; eq(column: string, value: string): Query; maybeSingle(): Promise<{ data: unknown; error: unknown }> }
interface Client { from(table: 'company_cost_settings'): Query }
export interface CostSettingsDataRepository { get(companyId: string, tenantId: string): Promise<CompanyCostSettings | null> }
export function createSupabaseCostSettingsRepository(db: UserSupabaseClient): CostSettingsDataRepository { const client = db as unknown as Client; return { async get(companyId, tenantId) { const { data, error } = await client.from('company_cost_settings').select('company_id, tenant_id, enabled, default_currency_code, money_scale, time_zone, version, created_at, updated_at').eq('tenant_id', tenantId).eq('company_id', companyId).maybeSingle(); const parsed = row.safeParse(data); if (error) throw new AppApiError(500, 'INTERNAL_ERROR', 'Không thể đọc cấu hình C1.'); if (data === null) return null; if (!parsed.success) throw new AppApiError(500, 'INTERNAL_ERROR', 'Không thể đọc cấu hình C1.'); return companyCostSettingsSchema.parse({ companyId: parsed.data.company_id, enabled: parsed.data.enabled, defaultCurrencyCode: parsed.data.default_currency_code, moneyScale: parsed.data.money_scale, timeZone: parsed.data.time_zone, version: parsed.data.version, createdAt: parsed.data.created_at, updatedAt: parsed.data.updated_at }) } } }
