export const permissionCodes = [
  'employee.read_directory',
  'employee.read_self_private',
  'employee.read_all',
  'employee.read_private',
  'employee.create',
  'employee.update',
  'employee.offboard',
  'account.invite',
  'account.disable',
  'role.read',
  'role.assign',
  'role.revoke',
  'supplier.read',
  'supplier.create',
  'supplier.update',
  'quotation_request.create',
  'quotation_request.update',
  'inventory.read',
  'stock_count.create',
  'stock_count.update',
  'stock_adjustment.read',
  'stock_adjustment.approve',
  'technical_document.read',
  'technical_document.update',
  'drawing.read',
  'drawing.create',
  'drawing.update',
  'accounting_document.read',
  'accounting_document.update',
  'supplier_payment.approve',
  'inventory_value.read',
  'project.read',
  'task.read_assigned',
  'task.update_assigned',
] as const

export type PermissionCode = (typeof permissionCodes)[number]
