import {describe,expect,it,vi} from 'vitest'
import {uploadWorkflowOriginal,type WorkflowUploadSession} from '../../../app/utils/costs/cost-workflow-uploader'
const company='c1f50000-0000-4000-8000-000000000001',project='c1f50000-0000-4000-8000-000000000002',fileId='c1f50000-0000-4000-8000-000000000003'
const file=new File(['synthetic'],'fixture.pdf',{type:'application/pdf'})
const intent={evidenceFileId:fileId,version:0,bucketId:'c1-accounting-evidence',objectPath:company+'/'+company+'/'+project+'/'+fileId,expiresAt:'2099-10-05T00:00:00Z',replayed:false}
const finalized={id:fileId,status:'finalized',originalFilename:file.name,mimeType:file.type,sizeBytes:file.size,sha256:'a'.repeat(64),version:1,finalizedAt:'2026-10-05T00:00:00Z',replayed:false}
function fixture(){const createEvidenceIntent=vi.fn(async()=>intent),finalizeEvidence=vi.fn(async()=>finalized),upload=vi.fn(async()=>({error:null}));return {createEvidenceIntent,finalizeEvidence,upload,repository:{createEvidenceIntent,finalizeEvidence} as never,supabaseClient:{storage:{from:vi.fn(()=>({upload}))}} as never}}
describe('workflow upload reuses verified immutable originals',()=>{
 it('preserves the workflow target and evidence kind without legacy linking',async()=>{const f=fixture();const result=await uploadWorkflowOriginal({...f,companyId:company,projectId:project,file,target:{kind:'request'},evidenceKind:'quotation',isScopeCurrent:()=>true});expect(result.evidenceFileId).toBe(fileId);expect(f.createEvidenceIntent.mock.calls[0]).toEqual([project,expect.objectContaining({target:{kind:'request'},evidenceKind:'quotation'}),expect.anything()]);expect(f.upload).toHaveBeenCalledOnce()})
 it('retries a lost finalization response with the same key and does not upload again',async()=>{const f=fixture();let session:WorkflowUploadSession|undefined;f.finalizeEvidence.mockRejectedValueOnce(new Error('network'));const options={...f,companyId:company,projectId:project,file,target:{kind:'request'} as const,evidenceKind:'quotation' as const,isScopeCurrent:()=>true,onSessionChange:(v:WorkflowUploadSession)=>{session=v}};await expect(uploadWorkflowOriginal(options)).rejects.toThrow('network');await uploadWorkflowOriginal({...options,session});expect(f.upload).toHaveBeenCalledOnce();expect(f.finalizeEvidence.mock.calls[0]).toEqual(f.finalizeEvidence.mock.calls[1])})
 it('rejects a different project path before Storage upload',async()=>{const f=fixture();f.createEvidenceIntent.mockResolvedValueOnce({...intent,objectPath:company+'/'+company+'/'+company+'/'+fileId});await expect(uploadWorkflowOriginal({...f,companyId:company,projectId:project,file,target:{kind:'request'},evidenceKind:'invoice',isScopeCurrent:()=>true})).rejects.toThrow('EVIDENCE_SCOPE_MISMATCH');expect(f.upload).not.toHaveBeenCalled()})
 it('stops a company or project switch before finalization and attachment',async()=>{const f=fixture();let current=true;f.upload.mockImplementationOnce(async()=>{current=false;return{error:null}});await expect(uploadWorkflowOriginal({...f,companyId:company,projectId:project,file,target:{kind:'request'},evidenceKind:'invoice',isScopeCurrent:()=>current})).rejects.toThrow('Ngữ cảnh');expect(f.finalizeEvidence).not.toHaveBeenCalled()})
})
