import {describe,expect,it,vi} from 'vitest'
import {createReviewedRequestSubmission} from '../../../app/utils/costs/cost-request-submission'
const id='c1f50000-0000-4000-8000-000000000001'
const input={partyId:id,partyKind:'organization',categoryId:id,amount:'10',currencyCode:'VND',basis:{kind:'materials',deliverySite:'Synthetic',lines:[{description:'pipe',quantity:'1',unit:'item',unitPrice:'10'}]},evidenceFileIds:[id]} as const
function fixture(){return {createRequest:vi.fn(async()=>({requestId:id,version:0,replayed:false})),updateRequest:vi.fn(async()=>({requestId:id,version:1,replayed:false})),submitRequest:vi.fn(async()=>({requestId:id,version:1,replayed:false}))}}
describe('reviewed request write and submit receipt recovery',()=>{
 it('retries a lost create response with identical payload/key instead of duplicating the request',async()=>{const r=fixture();r.createRequest.mockRejectedValueOnce(new Error('network'));const s=createReviewedRequestSubmission({projectId:id,repository:r as never,isScopeCurrent:()=>true});await expect(s.submit(input)).rejects.toThrow('network');await s.submit(input);expect(r.createRequest.mock.calls[0]).toEqual(r.createRequest.mock.calls[1]);expect(r.submitRequest).toHaveBeenCalledOnce()})
 it('keeps a successful create receipt and stable submit revision/key across response loss',async()=>{const r=fixture();r.submitRequest.mockRejectedValueOnce(new Error('network'));const s=createReviewedRequestSubmission({projectId:id,repository:r as never,isScopeCurrent:()=>true});await expect(s.submit(input)).rejects.toThrow();await s.submit(input);expect(r.createRequest).toHaveBeenCalledOnce();expect(r.submitRequest.mock.calls[0]).toEqual(r.submitRequest.mock.calls[1])})
 it('requires resolving an uncertain prior command before accepting edited input',async()=>{const r=fixture();r.submitRequest.mockRejectedValueOnce(new Error('network'));const s=createReviewedRequestSubmission({projectId:id,repository:r as never,isScopeCurrent:()=>true});await expect(s.submit(input)).rejects.toThrow();await expect(s.submit({...input,amount:'11'})).rejects.toThrow('REQUEST_RESPONSE_UNCERTAIN');expect(r.updateRequest).not.toHaveBeenCalled()})
 it('stops a scope switch between creation and submission without attaching the receipt',async()=>{const r=fixture();let current=true;r.createRequest.mockImplementationOnce(async()=>{current=false;return{requestId:id,version:0,replayed:false}});const s=createReviewedRequestSubmission({projectId:id,repository:r as never,isScopeCurrent:()=>current});await expect(s.submit(input)).rejects.toThrow('WORKFLOW_SCOPE_CHANGED');expect(r.submitRequest).not.toHaveBeenCalled()})
 it('updates a returned request using its exact captured version and a flattened strict body',async()=>{const r=fixture();const s=createReviewedRequestSubmission({projectId:id,repository:r as never,isScopeCurrent:()=>true,initial:{id,version:3}});await s.submit(input);expect(r.createRequest).not.toHaveBeenCalled();expect(r.updateRequest).toHaveBeenCalledWith(id,id,{...input,expectedVersion:3},expect.anything());expect(r.submitRequest).toHaveBeenCalledWith(id,id,{expectedVersion:1},expect.anything())})
})
