import {describe,expect,it,vi} from 'vitest'
import {CostWorkflowService,type WorkflowContext,type WorkflowRepository} from '../../../server/features/costs/workflow/cost-workflow.service'
import {SupabaseWorkflowRepository} from '../../../server/features/costs/workflow/cost-workflow.repository'
const id='c1f50000-0000-4000-8000-000000000001'
const context=(permissions:string[])=>({companyId:id,requestId:id,permissions}) as unknown as WorkflowContext
describe('workflow directory and immutable history boundary',()=>{
 it('permits a mode lookup for an existing legacy reader without granting workflow project access',async()=>{const readDirectory=vi.fn(async()=>({mode:'legacy',projects:[],nextCursor:null}));const s=new CostWorkflowService({readDirectory} as unknown as WorkflowRepository);await s.readDirectory(context(['cost.read']),{});expect(readDirectory).toHaveBeenCalledWith(context(['cost.read']),{pageSize:25})})
 it('requires an explicit read permission and validates bounded pagination before the repository',async()=>{const readDirectory=vi.fn();const s=new CostWorkflowService({readDirectory} as unknown as WorkflowRepository);await expect(s.readDirectory(context([]),{})).rejects.toMatchObject({code:'PERMISSION_DENIED'});await expect(s.readDirectory(context(['cost.request.read']),{pageSize:101})).rejects.toMatchObject({code:'INPUT_INVALID'});expect(readDirectory).not.toHaveBeenCalled()})
 it('keeps immutable history behind request read instead of legacy cost read',async()=>{const readRequestHistory=vi.fn(async()=>[]),s=new CostWorkflowService({readRequestHistory} as unknown as WorkflowRepository);await expect(s.readRequestHistory(context(['cost.read']),id,id)).rejects.toMatchObject({code:'PERMISSION_DENIED'});await s.readRequestHistory(context(['cost.request.read']),id,id);expect(readRequestHistory).toHaveBeenCalledOnce()})
 it('passes captured company, cursor and exact request scope to user-bound RPCs',async()=>{const rpc=vi.fn().mockResolvedValueOnce({data:{mode:'document_backed_v1',projects:[],nextCursor:null},error:null}).mockResolvedValueOnce({data:[],error:null});const r=new SupabaseWorkflowRepository({rpc} as never);await r.readDirectory(context(['cost.request.read']),{pageSize:25,afterId:id});await r.readRequestHistory(context(['cost.request.read']),id,id);expect(rpc.mock.calls).toEqual([['c1_workflow_directory',{target_company_id:id,target_after_id:id,target_page_size:25}],['c1_workflow_request_history',{target_company_id:id,target_project_id:id,target_id:id}]])})
})
