import {describe,expect,it,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import ExcelJS from 'exceljs'
import JSZip from 'jszip'
import {ExcelCostExtractionAdapter,OfflineCostExtractionAdapter} from '../../../server/features/costs/extraction/cost-extraction-adapter'
import {CostExtractionService} from '../../../server/features/costs/extraction/cost-extraction.service'
const id='c1f50000-0000-4000-8000-000000000001'
const mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
const context={actorId:id,tenantId:id,companyId:id,requestId:id,permissions:['cost.prepare','cost.request.submit','cost.request.file.read','cost.request.read'] as const}
const input=(bytes:Uint8Array)=>({fileId:id,mimeType:mime,bytes,scope:{companyId:id,projectId:id}})
async function workbook(rows:unknown[][]){const book=new ExcelJS.Workbook();const sheet=book.addWorksheet('Synthetic');for(const row of rows)sheet.addRow(row);return new Uint8Array(await book.xlsx.writeBuffer())}
describe('offline document extraction never posts cash or obligations',()=>{
 it('preserves materials, site, exact quantities/rates and accountant tax notes as review-only suggestions',async()=>{const bytes=await workbook([['Loại','materials'],['Nhà cung cấp','Synthetic HaiPower'],['Địa điểm giao','Synthetic project site'],['Thuế GTGT','Accountant reviews quoted VAT'],['Làm tròn','Accountant-defined rounding'],['Mô tả','Số lượng','Đơn vị','Đơn giá'],['Synthetic pipe','2.125','m','10.1234']]);const result=await new ExcelCostExtractionAdapter().extract(input(bytes));expect(result).toMatchObject({status:'needs_review',reviewRequired:true,fields:{partyHint:'Synthetic HaiPower',accountingBasis:{vatBasis:'Accountant reviews quoted VAT',roundingBasis:'Accountant-defined rounding'},basis:{kind:'materials',deliverySite:'Synthetic project site',lines:[{description:'Synthetic pipe',quantity:'2.125',unit:'m',unitPrice:'10.1234'}]}}});expect(result.sourceLocations.length).toBeGreaterThan(0)})
 it('keeps subcontract acceptance and warranty separate from actual cash',async()=>{const result=await new ExcelCostExtractionAdapter().extract(input(await workbook([['Loại','subcontract'],['Nhà cung cấp','Synthetic crew'],['Hợp đồng','Synthetic contract'],['Nghiệm thu','Synthetic acceptance'],['Giữ lại bảo hành','5']])));expect(result.fields.basis).toMatchObject({kind:'subcontract',contractReference:'Synthetic contract',acceptanceReference:'Synthetic acceptance',retentionAmount:'5'});expect(result.fields).not.toHaveProperty('paidAmount')})
 it('preserves crew week, worker-days, rates and allowance without calculating payroll policy',async()=>{const result=await new ExcelCostExtractionAdapter().extract(input(await workbook([['Loại','direct_labor'],['Tuần bắt đầu','2026-10-05'],['Đội','Synthetic internal crew'],['Nhân sự','Ngày công','Đơn giá ngày','Phụ cấp'],['Synthetic worker','4.5','100','20']])));expect(result.fields.basis).toMatchObject({kind:'direct_labor',weekStart:'2026-10-05',workers:[{workerReference:'Synthetic worker',days:'4.5',dailyRate:'100',allowance:'20'}]});expect(result.fields.amount).toBeUndefined()})
 it('returns unavailable for photos/PDF until a separately approved provider exists and makes no network call',async()=>{const spy=vi.spyOn(globalThis,'fetch');const adapter=new OfflineCostExtractionAdapter();for(const type of ['application/pdf','image/png','image/jpeg'])expect(await adapter.extract({...input(new Uint8Array([1,2,3])),mimeType:type})).toMatchObject({status:'unavailable',reviewRequired:true,warnings:['OCR_PROVIDER_NOT_CONFIGURED']});expect(spy).not.toHaveBeenCalled();spy.mockRestore()})
 it('rejects macro content and external relationships before Excel parsing',async()=>{const original=await workbook([['Loại','materials']]);for(const mode of ['macro','external']){const zip=await JSZip.loadAsync(original);if(mode==='macro')zip.file('xl/vbaProject.bin','synthetic');else zip.file('xl/_rels/external.rels','<Relationships><Relationship TargetMode="External" Target="https://example.invalid"/></Relationships>');const result=await new ExcelCostExtractionAdapter().extract(input(await zip.generateAsync({type:'uint8array'})));expect(result.status).toBe('failed');expect(result.warnings).toContain(mode==='macro'?'EXCEL_ACTIVE_CONTENT_UNSUPPORTED':'EXCEL_EXTERNAL_LINK_UNSUPPORTED')}})
 it('bounds compressed bytes, archive expansion, coordinates and malformed MIME without throwing document contents',async()=>{const adapter=new ExcelCostExtractionAdapter();expect(await adapter.extract(input(new Uint8Array(5*1024*1024+1)))).toMatchObject({status:'failed',warnings:['EXTRACTION_FILE_TOO_LARGE']});expect((await adapter.extract({...input(new Uint8Array([1])),mimeType:'application/vnd.ms-excel'})).status).toBe('unavailable');const zip=new JSZip();zip.file('[Content_Types].xml','x');zip.file('xl/workbook.xml','x');zip.file('xl/worksheets/sheet1.xml','x'.repeat(2*1024*1024+1));expect((await adapter.extract(input(await zip.generateAsync({type:'uint8array',compression:'DEFLATE'})))).status).toBe('failed')})
 it('does not accept ambiguous dates, cached formula money or auto-match a party identity',async()=>{const result=await new ExcelCostExtractionAdapter().extract(input(await workbook([['Loại','direct_labor'],['Tuần bắt đầu','2026-02-30'],['Tổng thanh toán',{formula:'1+1',result:2}],['Đội','Unknown crew']])));expect(result.status).toBe('needs_review');expect(result.warnings).toContain('INVALID_DATE_REQUIRES_REVIEW');expect(result.fields.amount).toBeUndefined();expect(result.fields).not.toHaveProperty('partyId')})

 it('rejects forged extreme cell/merge coordinates before workbook allocation',async()=>{const zip=await JSZip.loadAsync(await workbook([['Loại','materials']]));const path='xl/worksheets/sheet1.xml';const xml=await zip.file(path)!.async('string');zip.file(path,xml.replace('r="A1"','r="A99999999"'));expect(await new ExcelCostExtractionAdapter().extract(input(await zip.generateAsync({type:'uint8array'})))).toMatchObject({status:'failed',warnings:['EXCEL_COORDINATE_LIMIT']})})
 it('does not silently merge different worksheets into one party/basis',async()=>{const book=new ExcelJS.Workbook();book.addWorksheet('First').addRow(['Loại','materials']);book.addWorksheet('Second').addRow(['Loại','direct_labor']);expect(await new ExcelCostExtractionAdapter().extract(input(new Uint8Array(await book.xlsx.writeBuffer())))).toMatchObject({status:'needs_review',fields:{},warnings:['EXCEL_MULTIPLE_SHEETS_REQUIRE_REVIEW']})})
 it('retains exact numeric XML text beyond JavaScript floating point precision',async()=>{const zip=await JSZip.loadAsync(await workbook([['Loại','materials'],['Mô tả','Số lượng','Đơn vị','Đơn giá'],['Synthetic line','1','m',1]]));const path='xl/worksheets/sheet1.xml',xml=await zip.file(path)!.async('string');zip.file(path,xml.replace(/(<c r="D3"[^>]*><v>)1(<\/v>)/,'$19999999999999999.1234$2'));const result=await new ExcelCostExtractionAdapter().extract(input(await zip.generateAsync({type:'uint8array'})));expect(result.fields.basis).toMatchObject({kind:'materials',lines:[{unitPrice:'9999999999999999.1234'}]})})
 it('reads reviewed committed synthetic bytes with no real attachment or party creation',async()=>{const bytes=new Uint8Array(readFileSync('tests/fixtures/costs/extraction/materials.synthetic.xlsx'));expect(await new ExcelCostExtractionAdapter().extract(input(bytes))).toMatchObject({reviewRequired:true,fields:{partyHint:'Synthetic HaiPower',amount:'22'}})})
 it('authorizes before downloading and revalidates the exact file/request revision when storing',async()=>{const target={fileId:id,companyId:id,projectId:id,requestId:null,fileVersion:1,requestVersion:null,sha256:'a'.repeat(64),mimeType:'image/png'};const repository={readTarget:vi.fn().mockResolvedValue(target),download:vi.fn().mockResolvedValue(new Uint8Array([1])),persist:vi.fn().mockRejectedValue(new Error('VERSION_CONFLICT'))};await expect(new CostExtractionService(repository,new OfflineCostExtractionAdapter()).extract(context,id,null,id,id)).rejects.toThrow('VERSION_CONFLICT');expect(repository.persist.mock.calls[0]?.slice(0,4)).toEqual([context,id,target,expect.objectContaining({reviewRequired:true})])})
 it('rejects legacy-only permission and never reads unscoped originals',async()=>{const r={readTarget:vi.fn(),download:vi.fn(),persist:vi.fn()};await expect(new CostExtractionService(r,new OfflineCostExtractionAdapter()).extract({...context,permissions:['cost.read']},id,null,id,id)).rejects.toMatchObject({statusCode:403});expect(r.readTarget).not.toHaveBeenCalled();expect(r.download).not.toHaveBeenCalled()})
})
