import { describe, expect, it, vi } from 'vitest'
import { CostWorkflowService } from '../../../server/features/costs/workflow/cost-workflow.service'
const id='c1f50000-0000-4000-8000-000000000001'
const project='c1f50000-0000-4000-8000-000000000002'
const context={actorId:id,tenantId:id,companyId:id,requestId:id,permissions:['cost.request.submit','cost.request.read'] as const}
const input={partyId:id,partyKind:'organization',categoryId:id,amount:'70',currencyCode:'VND',basis:{kind:'materials',lines:[{description:'pipe',quantity:'1',unit:'item',unitPrice:'70'}],deliverySite:'synthetic site'},evidenceFileIds:[id]}
function repository(){return {readDirectory:vi.fn(),readRequestHistory:vi.fn(),readProjectContext:vi.fn(),listSourceSubcontracts:vi.fn(),listContracts:vi.fn(),listAdjustments:vi.fn(),readAdjustment:vi.fn(),createRequest:vi.fn(async()=>({requestId:id,version:0,replayed:false})),updateRequest:vi.fn(),submitRequest:vi.fn(),decideRequest:vi.fn(),assignManager:vi.fn(),createContractBasis:vi.fn(),submitContractAdjustment:vi.fn(),decideContractAdjustment:vi.fn(),listRequests:vi.fn(async()=>[]),readRequest:vi.fn(),readContract:vi.fn(),listNotifications:vi.fn(async()=>[]),markNotificationRead:vi.fn()}}
describe('document backed request service',()=>{
 it('requires a party and finalized evidence identities before requesting a durable record',async()=>{const r=repository();const s=new CostWorkflowService(r);await expect(s.createRequest(context,project,{...input,partyId:undefined},id)).rejects.toMatchObject({statusCode:400});await expect(s.createRequest(context,project,{...input,evidenceFileIds:[]},id)).rejects.toMatchObject({statusCode:400});expect(r.createRequest).not.toHaveBeenCalled()})
 it('rejects client actor/tenant and manager authority flags',async()=>{const r=repository();await expect(new CostWorkflowService(r).createRequest(context,project,{...input,approvedBy:id},id)).rejects.toMatchObject({statusCode:400});expect(r.createRequest).not.toHaveBeenCalled()})
 it('cannot let an accountant decide with submission permission',async()=>{const r=repository();await expect(new CostWorkflowService(r).decideRequest(context,project,id,{submittedVersionId:id,decision:'approve'},id)).rejects.toMatchObject({statusCode:403});expect(r.decideRequest).not.toHaveBeenCalled()})
 it('cannot let assignment capability substitute for manager decision',async()=>{const r=repository();await expect(new CostWorkflowService(r).decideRequest({...context,permissions:['project.cost_manager.assign']},project,id,{submittedVersionId:id,decision:'approve'},id)).rejects.toMatchObject({statusCode:403})})
 it('requires a nonempty reason when returning an immutable snapshot',async()=>{const r=repository();await expect(new CostWorkflowService(r).decideRequest({...context,permissions:['cost.request.decide']},project,id,{submittedVersionId:id,decision:'return',reason:' '},id)).rejects.toMatchObject({statusCode:400});expect(r.decideRequest).not.toHaveBeenCalled()})
 it('passes submitted snapshot identity and route scope to the transaction boundary',async()=>{const r=repository();const decision={submittedVersionId:id,decision:'approve'};await new CostWorkflowService(r).decideRequest({...context,permissions:['cost.request.decide']},project,id,decision,id);expect(r.decideRequest).toHaveBeenCalledWith({...context,permissions:['cost.request.decide']},project,id,decision,id)})
 it('rechecks current assignment at the repository rather than treating company permission as approval',async()=>{const r=repository();r.decideRequest.mockRejectedValueOnce(Object.assign(new Error('old manager'),{statusCode:403}));await expect(new CostWorkflowService(r).decideRequest({...context,permissions:['cost.request.decide']},project,id,{submittedVersionId:id,decision:'approve'},id)).rejects.toMatchObject({statusCode:403})})
 it('cannot submit by supplying a manager or mutable snapshot payload',async()=>{const r=repository();await expect(new CostWorkflowService(r).submitRequest(context,project,id,{expectedVersion:0,managerUserId:id,snapshot:input},id)).rejects.toMatchObject({statusCode:400});expect(r.submitRequest).not.toHaveBeenCalled()})
 it('requires an optimistic version and reason for manager handover',async()=>{const r=repository();await expect(new CostWorkflowService(r).assignManager({...context,permissions:['project.cost_manager.assign']},project,{managerUserId:id,reason:'handover'},id)).rejects.toMatchObject({statusCode:400})})
 it('reviewed quote creation is a separate command from installment approval',async()=>{const r=repository();const basis={partyId:id,reference:'quote',referenceAmount:'100',currencyCode:'VND',evidenceFileIds:[id]};await new CostWorkflowService(r).createContractBasis(context,project,basis,id);expect(r.createContractBasis).toHaveBeenCalledWith(context,project,basis,id);expect(r.decideRequest).not.toHaveBeenCalled()})
})
