import {describe,expect,it} from 'vitest'
import {projectWorkflowCash} from '../../../server/features/costs/finance/cost-workflow-summary'
import {reconcileLegacyCashInputSchema} from '../../../shared/schemas/costs/cost-workflow-reporting'
const id='c1f50000-0000-4000-8000-000000000001'
const category=(code:string)=>({categoryId:id,code,name:code,displayOrder:1,outgoing:[],refunds:[],installments:[],unreconciledCount:0,verifiedLegacyCount:0,retention:{state:'not_recorded' as const,amount:null,recordedCount:0}})
const project={projectId:id,projectCode:'SYNTHETIC',projectName:'Synthetic project',currencyCode:'VND',moneyScale:0,timeZone:'Asia/Ho_Chi_Minh',operationalState:'active' as const}
describe('verified cash projection',()=>{
 it('never treats ordinary totals, invoices, sources or approvals as actual cash',()=>{const c={...category('materials'),unreconciledCount:1,installments:[{id,authorized:'100',consumed:'0'}]};const result=projectWorkflowCash({project,categories:[c]});expect(result.workflowCash).toMatchObject({grossPaid:'0.0000',approvedUnspent:'100.0000',coverage:'partial',unreconciledCount:1})})
 it('counts a canonical cash identity once while retaining gross, refunds and authority independently',()=>{const c={...category('subcontract_labor'),outgoing:[{id,validAmount:'10'},{id,validAmount:'10'}],refunds:[{id,paymentId:id,confirmedAmount:'2'}],installments:[{id,authorized:'30',consumed:'10'}],retention:{state:'recorded' as const,amount:'5.0000',recordedCount:1}};const result=projectWorkflowCash({project,categories:[c]});expect(result.workflowCash).toMatchObject({grossPaid:'10.0000',confirmedRefunds:'2.0000',netCash:'8.0000',approvedUnspent:'20.0000'});expect(result.categories[0]?.retention.amount).toBe('5.0000')})
 it('distinguishes unknown, verified zero and complete positive coverage',()=>{const empty=projectWorkflowCash({project,categories:[category('other')]});expect(empty.workflowCash.coverage).toBe('not_recorded');const verified=projectWorkflowCash({project,categories:[{...category('other'),verifiedLegacyCount:1}]});expect(verified.workflowCash.coverage).toBe('complete');expect(verified.workflowCash.grossPaid).toBe('0.0000')})
 it.each(['materials','subcontract_labor','direct_labor','machinery','other'])('uses identical cash semantics for %s',code=>{const result=projectWorkflowCash({project,categories:[{...category(code),outgoing:[{id,validAmount:'3'}]}]});expect(result.schemaVersion).toBe(2);expect(result.categories[0]?.workflowCash.netCash).toBe('3.0000')})
 it('rejects a cash identity appearing in different categories rather than double count',()=>{expect(()=>projectWorkflowCash({project,categories:[{...category('materials'),outgoing:[{id,validAmount:'10'}]},{...category('other'),outgoing:[{id,validAmount:'10'}]}]})).toThrow('CONFLICTING_CASH_CATEGORY')})
 it('keeps explicit zero reconciliation documented without inventing a payment date',()=>{const input={legacyKind:'ordinary_detail',legacyId:id,actualOutgoing:'0',actualPaymentDate:null,evidenceFileIds:[id],reason:'Reviewed no cash',expectedLegacyHash:'a'.repeat(64)};expect(reconcileLegacyCashInputSchema.safeParse(input).success).toBe(true);expect(reconcileLegacyCashInputSchema.safeParse({...input,actualOutgoing:'5'}).success).toBe(false);expect(reconcileLegacyCashInputSchema.safeParse({...input,actualOutgoing:'5',actualPaymentDate:'2026-02-30'}).success).toBe(false);expect(reconcileLegacyCashInputSchema.safeParse({...input,evidenceFileIds:[]}).success).toBe(false)})
})
