import { describe, expect, it, vi } from 'vitest'
import type { H3Event } from 'h3'
import { createCostWorkflowRoutes } from '../../../server/features/costs/workflow/cost-workflow.routes'
import { SupabaseWorkflowRepository } from '../../../server/features/costs/workflow/cost-workflow.repository'
vi.mock('h3',()=>({getRouterParam:(event:H3Event,name:string)=>event.context.params?.[name],getHeader:(event:H3Event,name:string)=>event.context.headers?.[name],readBody:async(event:H3Event)=>event.context.body}))
const company='c1f50000-0000-4000-8000-000000000001',project='c1f50000-0000-4000-8000-000000000002',id='c1f50000-0000-4000-8000-000000000003'
const context={companyId:company,tenantId:company,actorId:id,requestId:id,permissions:['cost.request.decide'] as const,db:{}}
function event(body:unknown={},key:string|undefined=id){return {context:{params:{companyId:company,projectId:project,requestId:id},headers:{'idempotency-key':key},body}} as unknown as H3Event}
describe('cost workflow HTTP boundary',()=>{
 it('rejects missing idempotency key before any command',async()=>{const decideRequest=vi.fn();const routes=createCostWorkflowRoutes({resolveContext:vi.fn(async()=>context),service:{decideRequest} as never});await expect(routes.decideRequest(event({submittedVersionId:id,decision:'approve'},''))).rejects.toMatchObject({statusCode:400});expect(decideRequest).not.toHaveBeenCalled()})
 it('rejects client authority and preserves trusted route scope',async()=>{const decideRequest=vi.fn(async()=>({requestId:id,version:2,replayed:false}));const routes=createCostWorkflowRoutes({resolveContext:vi.fn(async()=>context),service:{decideRequest} as never});await expect(routes.decideRequest(event({submittedVersionId:id,decision:'approve',managerUserId:id}))).rejects.toMatchObject({statusCode:400});expect(decideRequest).not.toHaveBeenCalled();await routes.decideRequest(event({submittedVersionId:id,decision:'approve'}));expect(decideRequest).toHaveBeenCalledWith(context,project,id,{submittedVersionId:id,decision:'approve'},id)})
 it('uses the user-bound RPC and server request correlation, not a browser actor',async()=>{const rpc=vi.fn(async()=>({data:{requestId:id,version:2,replayed:true},error:null}));const r=new SupabaseWorkflowRepository({rpc} as never);expect(await r.decideRequest(context,project,id,{submittedVersionId:id,decision:'approve'},id)).toEqual({requestId:id,version:2,replayed:true});expect(rpc).toHaveBeenCalledWith('c1_workflow_decide_request',{target_company_id:company,target_project_id:project,target_id:id,target_input:{submittedVersionId:id,decision:'approve'},target_idempotency_key:id,target_request_id:id})})
 it('maps capacity conflict without exposing raw database errors',async()=>{const rpc=vi.fn(async()=>({data:null,error:{message:'CONTRACT_CAP_EXCEEDED'}}));await expect(new SupabaseWorkflowRepository({rpc} as never).submitRequest(context,project,id,{expectedVersion:1},id)).rejects.toMatchObject({statusCode:409,code:'CONTRACT_CAP_EXCEEDED'});rpc.mockResolvedValueOnce({data:null,error:{message:'sensitive sql'}});await expect(new SupabaseWorkflowRepository({rpc} as never).submitRequest(context,project,id,{expectedVersion:1},id)).rejects.toMatchObject({statusCode:500,code:'INTERNAL_ERROR'})})
 it('rejects malformed RPC responses instead of returning forged authority',async()=>{const rpc=vi.fn(async()=>({data:{requestId:id,version:2,replayed:false,approvedBy:id},error:null}));await expect(new SupabaseWorkflowRepository({rpc} as never).submitRequest(context,project,id,{expectedVersion:1},id)).rejects.toMatchObject({statusCode:500})})
})
