import {describe,expect,it,vi} from 'vitest'
import {CostWorkflowCashService} from '../../../server/features/costs/workflow/cost-workflow-cash.service'
const id='c1f50000-0000-4000-8000-000000000001'
const context={actorId:id,tenantId:id,companyId:id,requestId:id,permissions:['cost.record_cash','cost.correct','cost.request.submit'] as const}
const payment={amount:'10',currencyCode:'VND',paymentDate:'2026-10-04',reference:'synthetic transfer',evidenceFileIds:[id],expectedVersion:0}
function repository(){return {confirmPayment:vi.fn(),createCashAdjustment:vi.fn(),decideCashAdjustment:vi.fn(),confirmRefund:vi.fn(),applyCashCorrection:vi.fn()}}
describe('proof-backed cash command boundary',()=>{
 it('requires payment proof and never accepts browser consumption or actor fields',async()=>{const r=repository(),s=new CostWorkflowCashService(r);await expect(s.confirmPayment(context,id,id,{...payment,evidenceFileIds:[]},id)).rejects.toMatchObject({statusCode:400});await expect(s.confirmPayment(context,id,id,{...payment,remaining:'90'},id)).rejects.toMatchObject({statusCode:400});expect(r.confirmPayment).not.toHaveBeenCalled()})
 it('approval authority cannot replace accountant actual-payment authority',async()=>{const r=repository();await expect(new CostWorkflowCashService(r).confirmPayment({...context,permissions:['cost.request.decide']},id,id,payment,id)).rejects.toMatchObject({statusCode:403});expect(r.confirmPayment).not.toHaveBeenCalled()})
 it('keeps correction and actual refund commands distinct',async()=>{const r=repository(),s=new CostWorkflowCashService(r);const correction={kind:'correction',correctedOutgoing:'8',reason:'wrong cash entry',evidenceFileIds:[id],expectedVersion:0};await s.createCashAdjustment(context,id,id,correction,id);expect(r.createCashAdjustment).toHaveBeenCalledWith(context,id,id,correction,id);expect(r.confirmRefund).not.toHaveBeenCalled();expect(r.confirmPayment).not.toHaveBeenCalled()})
 it('requires current manager capability and a reason for returning adjustments',async()=>{const r=repository(),s=new CostWorkflowCashService(r);await expect(s.decideCashAdjustment(context,id,id,{submittedVersionId:id,decision:'approve'},id)).rejects.toMatchObject({statusCode:403});await expect(s.decideCashAdjustment({...context,permissions:['cost.request.decide']},id,id,{submittedVersionId:id,decision:'return'},id)).rejects.toMatchObject({statusCode:400})})
 it('requires positive actual refund, civil receipt date and supporting proof',async()=>{const r=repository(),s=new CostWorkflowCashService(r);for(const input of [{amount:'0',receivedDate:'2026-10-04',evidenceFileIds:[id],expectedVersion:2},{amount:'2',receivedDate:'2026-02-30',evidenceFileIds:[id],expectedVersion:2},{amount:'2',receivedDate:'2026-10-04',evidenceFileIds:[],expectedVersion:2}])await expect(s.confirmRefund(context,id,id,input,id)).rejects.toMatchObject({statusCode:400});expect(r.confirmRefund).not.toHaveBeenCalled()})
 it('cannot supply a capacity reset or new amount when applying a reviewed correction',async()=>{const r=repository();await expect(new CostWorkflowCashService(r).applyCashCorrection(context,id,id,{expectedVersion:2,restoreAuthority:true},id)).rejects.toMatchObject({statusCode:400});expect(r.applyCashCorrection).not.toHaveBeenCalled()})
})
