import {describe,it,expect,beforeAll} from 'vitest'
import {readFileSync} from 'node:fs'
import {resolve} from 'node:path'
let m:typeof import('../../../scripts/c1-cost-workflow-rehearsal-all-sequences.mjs')|undefined
beforeAll(async()=>{try{m=await import('../../../scripts/c1-cost-workflow-rehearsal-all-sequences.mjs')}catch(e){if(!e||typeof e!=='object'||!('code'in e)||e.code!=='ERR_MODULE_NOT_FOUND')throw e}})
const implemented=()=>{expect(m,'complete sequence census is missing').toBeDefined();return m!}
function row(){const value=JSON.parse(readFileSync(resolve('.superpowers/sdd/2026-10-04-document-backed-installment-approval/pgtap-99407dbe-f340-4646-a275-6dcc6672c173-all-sequences-after.json'),'utf8'));value.sequences=JSON.parse(value.sequences);return value}
describe('complete sequence accounting preserves the existing two exceptions',()=>{
 it('reads every namespace without allocation or a larger output allowance',()=>{const n=implemented();expect(n.workflowAllSequenceSnapshotSql).toContain('join pg_catalog.pg_sequence');expect(n.workflowAllSequenceSnapshotSql).not.toMatch(/nspname in|\b(?:nextval|setval|create|insert|update|delete)\b/i);expect(n.workflowAllSequencePolicy.inventory).toHaveLength(5);expect(n.workflowAllSequencePolicy.total).toEqual([120,12]);expect(n.workflowAllSequencePolicy.unapprovedAllocationAllowance).toBe(0)})
 it('decodes and validates all five OID-keyed counters',()=>{const r=row(),n=implemented();expect(n.workflowAllSequenceSnapshot({rows:[{...r,sequences:JSON.stringify(r.sequences)}]})).toEqual(r)})
 it.each(['missing','extra','renamed','wrong-oid'])('rejects %s sequence inventory',kind=>{const r=row(),n=implemented();if(kind==='missing')delete r.sequences['17263'];else if(kind==='extra')r.sequences['99999']={...r.sequences['17263'],oid:'99999'};else if(kind==='renamed')r.sequences['17263'].name='another';else{r.sequences['99999']=r.sequences['17263'];delete r.sequences['17263']}expect(()=>n.workflowAllSequenceSnapshot({rows:[r]})).toThrow('ALL_SEQUENCE')})
 it.each(['16510','17263','21159'])('rejects allocation from nonbudget sequence OID %s',oid=>{const before=row(),after=row(),n=implemented();after.sequences[oid].lastValue=String(BigInt(after.sequences[oid].lastValue)+1n);after.sequences[oid].isCalled=true;expect(()=>n.assertWorkflowAllSequencePostflight(before,after,1,[0n,0n])).toThrow('UNAPPROVED_SEQUENCE_CHANGE')})
 it('admits only the existing audit and role ceilings and returns the same BigInt accounting',()=>{const before=row(),after=row(),n=implemented();after.sequences['20603'].lastValue=String(BigInt(after.sequences['20603'].lastValue)+20n);after.sequences['20827'].lastValue=String(BigInt(after.sequences['20827'].lastValue)+4n);const result=n.assertWorkflowAllSequencePostflight(before,after,1,[0n,0n]);expect(result.allocations).toEqual([20n,4n]);expect(result.cumulative).toEqual([20n,4n]);expect(()=>n.assertWorkflowAllSequencePostflight(before,after,0,[0n,0n])).toThrow('SEQUENCE_BUDGET');expect(()=>n.assertWorkflowAllSequencePostflight(before,after,1,[110n,10n])).toThrow('SEQUENCE_BUDGET')})
 it.each(['schemaOid','ownerOid','aclSha256','cache','increment'])('rejects %s metadata drift even on an approved exception',key=>{const before=row(),after=row(),n=implemented();after.sequences['20603'][key]=key==='aclSha256'?'f'.repeat(64):'2';expect(()=>n.assertWorkflowAllSequencePostflight(before,after,1,[0n,0n])).toThrow('SEQUENCE')})
 it('requires exact same-transaction census before any DDL and verifies historical overlap',()=>{const r=row(),n=implemented();expect(n.workflowAllSequenceAdmissionSql(r)).toContain('WORKFLOW_REHEARSAL_ALL_SEQUENCE_ADMISSION_CHANGED');const full={snapshot:{sequences:{'public.audit_events_id_seq':{lastValue:r.sequences['20603'].lastValue,isCalled:true,increment:'1',cache:'1',cycle:false}}}};expect(()=>n.assertWorkflowAllSequenceOverlap(full,r)).not.toThrow();full.snapshot.sequences['public.audit_events_id_seq'].lastValue='0';expect(()=>n.assertWorkflowAllSequenceOverlap(full,r)).toThrow('ALL_SEQUENCE')})
})
