import {readFileSync} from 'node:fs'
import {expect,it} from 'vitest'
const cash=readFileSync('supabase/migrations/20261004210400_c1_cost_workflow_cash_commands.sql','utf8')
const reconciliation=readFileSync('supabase/migrations/20261004210500_c1_cost_workflow_reconciliation.sql','utf8')
function fn(sql:string,name:string){const matches=[...sql.matchAll(new RegExp('create(?: or replace)? function '+name+'\\(','g'))];const begin=matches.at(-1)?.index??-1;expect(begin).toBeGreaterThanOrEqual(0);return sql.slice(begin,sql.indexOf('$$;',sql.indexOf('as $$',begin)+5)+3)}
it('cash commands bind original proof to the precise outgoing or refund target',()=>{const pay=fn(cash,'public.c1_workflow_confirm_payment'),refund=fn(cash,'public.c1_workflow_confirm_refund');expect(pay).toContain("private.c1_workflow_require_cash_target_proof(t,target_company_id,target_project_id,ids,'payment',installment.id,null)");expect(refund).toContain("private.c1_workflow_require_cash_target_proof(t,target_company_id,target_project_id,ids,'adjustment',request.id,payment.id)");const proof=fn(cash,'private.c1_workflow_require_cash_target_proof');expect(proof).toContain('f.workflow_target_id=expected_target_id');expect(proof).toContain("f.workflow_target_kind='adjustment_source'");expect(proof).toContain('f.workflow_target_id=expected_source_payment_id')})
it('historical cash review remains separate from new targeted outgoing/refund commands',()=>{expect(reconciliation).toContain('private.c1_workflow_require_cash_proof(t,target_company_id,target_project_id,ids)')})
it('the final cap guard conservatively blocks published ordinary historical obligations for the same party/project',()=>{const guard=fn(reconciliation,'private.c1_workflow_require_cap');expect(guard).toContain('public.project_cost_items legacy');expect(guard).toContain('legacy.party_id=contract.party_id or legacy.party_id is null');expect(guard).toContain("legacy.publication_state='published'");expect(guard).toContain('legacy.tenant_id=t and legacy.company_id=c and legacy.project_id=p');expect(guard).toContain("message='LEGACY_RECONCILIATION_REQUIRED'")})

it('serializes cash proof hash claims and rejects reuse instead of trusting an editable reference',()=>{const pay=fn(cash,'public.c1_workflow_confirm_payment'),refund=fn(cash,'public.c1_workflow_confirm_refund');expect(pay).toContain('private.c1_workflow_require_unused_cash_proof(t,target_company_id,target_project_id,ids)');expect(refund).toContain('private.c1_workflow_require_unused_cash_proof(t,target_company_id,target_project_id,ids)');const claims=fn(cash,'private.c1_workflow_require_unused_cash_proof');expect(claims).toContain('pg_advisory_xact_lock');expect(claims).toContain('known.verified_sha256=proof_hash');expect(claims).toContain("message='CASH_DUPLICATE_EVENT'");expect(pay).not.toContain("'date',payment_date,'reference',reference")})
it('uses verified primary basis originals to reject a renamed second cap while allowing other supporting originals',()=>{const requests=readFileSync('supabase/migrations/20261004210300_c1_cost_workflow_request_commands.sql','utf8');const basis=fn(requests,'public.c1_workflow_create_contract_basis');expect(basis).toContain('private.c1_workflow_primary_basis_hashes');expect(basis).toContain('known.verified_sha256=any(original_hashes)');expect(basis.indexOf('c1_workflow_lock_assignment')).toBeLessThan(basis.indexOf('known.verified_sha256=any(original_hashes)'));const primary=fn(requests,'private.c1_workflow_primary_basis_hashes');expect(primary).toContain("f.workflow_evidence_kind in('contract','quotation')")})

it('backs proof race exclusion with immutable company-scoped database uniqueness',()=>{expect(cash).toContain('primary key(tenant_id,company_id,proof_sha256)');expect(cash).toContain('alter table public.cost_workflow_cash_proof_claims force row level security');expect(fn(cash,'public.c1_workflow_confirm_payment')).toContain('private.c1_workflow_claim_cash_proof(t,target_company_id,target_project_id,ids,payment.id,null)');expect(fn(cash,'public.c1_workflow_confirm_refund')).toContain('private.c1_workflow_claim_cash_proof(t,target_company_id,target_project_id,ids,null,refund.id)');expect(reconciliation).toContain('private.c1_workflow_claim_cash_proof(t,target_company_id,target_project_id,ids,payment_id,null)')})

it('explicit contract version selection cannot bypass primary original identity',()=>{const extraction=readFileSync('supabase/migrations/20261004210600_c1_cost_workflow_extraction.sql','utf8');const validate=fn(extraction,'private.c1_workflow_validate_request');expect(validate).toContain('v.contract_id<>contract.id');expect(validate).toContain('known.verified_sha256=any(private.c1_workflow_primary_basis_hashes(t,c,p,v.evidence_file_ids))');expect(validate).toContain("message='CONTRACT_REFERENCE_CONFLICT'")})
