import {mkdtempSync,readFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {beforeAll,describe,expect,it} from 'vitest'
import {resolve,join} from 'node:path'
import {pathToFileURL} from 'node:url'
import {workflowSha} from '../../../scripts/c1-cost-workflow-rehearsal-inventory.mjs'
import {workflowSequenceNames} from '../../../scripts/c1-cost-workflow-rehearsal-catalog.mjs'
let native:typeof import('../../../scripts/c1-cost-workflow-rehearsal-native.mjs')|undefined
beforeAll(async()=>{try{native=await import(pathToFileURL(resolve(process.cwd(),'scripts/c1-cost-workflow-rehearsal-native.mjs')).href)}catch(error){if(!(error instanceof Error)||!('code' in error)||error.code!=='ERR_MODULE_NOT_FOUND')throw error}})
function implemented(){expect(native,'native expiry comparison source is missing').toBeDefined();return native!}
const time='2026-10-05T13:00:00.123456Z'
function row(expiry='2026-10-05T13:04:59.123456Z'){
 const objects=[{kind:'role',identity:'17487',sha256:workflowSha(expiry),metadata:{oid:17487,rolname:'cli_login_postgres',rolvaliduntil:expiry,rolcanlogin:true,rolsuper:false,rolpassword:'********'}},{kind:'namespace',identity:'2200',sha256:'b'.repeat(64),metadata:{oid:2200,nspname:'public',nspowner:10,nspacl:null}}]
 delete (objects[0]!.metadata as Partial<typeof objects[0]['metadata']>).rolpassword
 const counter={lastValue:'1',isCalled:false,increment:'1',cache:'1',cycle:false}
 return {snapshot:{tables:{'public.history':{count:1,sha256:'c'.repeat(64)}},sequences:Object.fromEntries(workflowSequenceNames.map((name:string)=>[name,{...counter}])),catalogueSha256:workflowSha(expiry),catalogueComparableSha256:'d'.repeat(64),catalogueObjectCount:objects.length,catalogueObjectHashesSha256:workflowSha(objects.map(o=>o.sha256).join('\n')),catalogueObjects:objects},server_time:time,database:'postgres',username:'cli_login_postgres'}
}
function reseal(r:ReturnType<typeof row>){r.snapshot.catalogueObjectCount=r.snapshot.catalogueObjects.length;r.snapshot.catalogueObjectHashesSha256=workflowSha(r.snapshot.catalogueObjects.map(o=>o.sha256).join('\n'));return r}
describe('approved native CLI expiry boundary',()=>{
 it('accepts only monotonic existing-role expiry refresh and reports both original values',()=>{const a=row(),b=row('2026-10-05T13:05:00.123456Z');expect(implemented().assertWorkflowNativeCatalogue(a,b)).toEqual({roleOid:'17487',roleName:'cli_login_postgres',field:'rolvaliduntil',before:a.snapshot.catalogueObjects[0]!.metadata.rolvaliduntil,after:b.snapshot.catalogueObjects[0]!.metadata.rolvaliduntil})})
 it('accepts exact catalogue equality without reporting a change',()=>{expect(implemented().assertWorkflowNativeCatalogue(row(),row())).toBeNull()})
 it.each(['2026-10-05T13:05:00.123457Z','infinity',null])('rejects unbounded or invalid expiry %s',(expiry)=>{const r=row();r.snapshot.catalogueObjects[0]!.metadata.rolvaliduntil=expiry as string;expect(()=>implemented().assertWorkflowNativeSnapshot(r)).toThrow('CLI_EXPIRY')})
 it('rejects submillisecond expiry regression',()=>{expect(()=>implemented().assertWorkflowNativeCatalogue(row(),row('2026-10-05T13:04:59.123455Z'))).toThrow('CLI_EXPIRY')})
 it.each(['rolsuper','rolcanlogin'])('rejects other managed-role attribute changes %s',(field)=>{const b=row('2026-10-05T13:05:00.123456Z');b.snapshot.catalogueObjects[0]!.metadata[field as 'rolsuper']=true; if(field==='rolcanlogin')b.snapshot.catalogueObjects[0]!.metadata.rolcanlogin=false;expect(()=>implemented().assertWorkflowNativeCatalogue(row(),b)).toThrow('POSTFLIGHT_DRIFT')})
 it('rejects role recreation with another OID',()=>{const r=row();r.snapshot.catalogueObjects[0]!.metadata.oid=17488;r.snapshot.catalogueObjects[0]!.identity='17488';expect(()=>implemented().assertWorkflowNativeSnapshot(r)).toThrow('CLI_ROLE')})
 it('rejects role rename or missing role',()=>{const r=row();r.snapshot.catalogueObjects[0]!.metadata.rolname='other';expect(()=>implemented().assertWorkflowNativeSnapshot(r)).toThrow('CLI_ROLE');r.snapshot.catalogueObjects.shift();expect(()=>implemented().assertWorkflowNativeSnapshot(reseal(r))).toThrow('CLI_ROLE')})
 it('rejects other objects and canonical comparable digest drift',()=>{const b=row('2026-10-05T13:05:00.123456Z');b.snapshot.catalogueObjects[1]!.sha256='e'.repeat(64);expect(()=>implemented().assertWorkflowNativeCatalogue(row(),reseal(b))).toThrow('POSTFLIGHT_DRIFT');const c=row();c.snapshot.catalogueComparableSha256='f'.repeat(64);expect(()=>implemented().assertWorkflowNativeCatalogue(row(),c)).toThrow('POSTFLIGHT_DRIFT')})
 it('rejects unexplained aggregate drift with identical expiry',()=>{const b=row();b.snapshot.catalogueSha256='e'.repeat(64);expect(()=>implemented().assertWorkflowNativeCatalogue(row(),b)).toThrow('POSTFLIGHT_DRIFT')})
 it('keeps table and every sequence guard in native postflight',()=>{const a=row(),b=row();b.snapshot.tables['public.history'].count++;expect(()=>implemented().assertWorkflowNativePostflight(a,b,0)).toThrow('POSTFLIGHT_DRIFT');const c=row();c.snapshot.sequences[workflowSequenceNames[0]!]!.isCalled=true;expect(()=>implemented().assertWorkflowNativePostflight(a,c,0)).toThrow('SEQUENCE_BUDGET')})
 it('binds full baseline bytes to the exact source manifest',()=>{const m='a'.repeat(64),b=implemented().workflowNativeBaseline(m,row());expect(implemented().assertWorkflowNativeBaseline(b,m,b.sha256)).toEqual(b);expect(()=>implemented().assertWorkflowNativeBaseline(b,'b'.repeat(64),b.sha256)).toThrow('BASELINE');b.row.snapshot.tables['public.history'].count++;expect(()=>implemented().assertWorkflowNativeBaseline(b,m,b.sha256)).toThrow('BASELINE')})
 it('preserves raw catalogue and emits separate comparable hash in a read-only snapshot',()=>{const sql=implemented().workflowNativeSnapshotSql;expect(sql).toContain('begin isolation level repeatable read read only;');expect(sql).toContain("'catalogueComparableSha256',comparable_hash");expect(sql).toContain("payload->>'oid'='17487'");expect(sql).toContain("payload->>'rolname'='cli_login_postgres'");expect(sql).toContain("payload-'rolvaliduntil'");expect(sql.trim().endsWith('rollback;')).toBe(true);expect(sql).not.toMatch(/alter\s+role|setval\s*\(/i)})
})

describe('one-use native retry reservation',()=>{
 it('consumes the approved manifest once even if another baseline is later captured',()=>{const dir=mkdtempSync(join(tmpdir(),'taskovia-native-reservation-')),manifest='a'.repeat(64);try{implemented().reserveWorkflowNativeRetry(dir,manifest,'b'.repeat(64),'first');expect(()=>implemented().reserveWorkflowNativeRetry(dir,manifest,'c'.repeat(64),'second')).toThrow('RETRY_ALREADY_CONSUMED');expect(JSON.parse(readFileSync(join(dir,'native-retry-'+manifest+'.started.json'),'utf8')).baselineSha256).toBe('b'.repeat(64))}finally{rmSync(dir,{recursive:true,force:true})}})
 it('checks final cumulative ceilings without reducing them to the cash-suite ceiling',()=>{const a=row(),b=row();b.snapshot.sequences[workflowSequenceNames[0]!]!.lastValue='120';b.snapshot.sequences[workflowSequenceNames[0]!]!.isCalled=true;b.snapshot.sequences[workflowSequenceNames[1]!]!.lastValue='12';b.snapshot.sequences[workflowSequenceNames[1]!]!.isCalled=true;expect(implemented().assertWorkflowNativePostflight(a,b,'total').allocations).toEqual([120n,12n]);b.snapshot.sequences[workflowSequenceNames[0]!]!.lastValue='121';expect(()=>implemented().assertWorkflowNativePostflight(a,b,'total')).toThrow('SEQUENCE_BUDGET')})
})

describe('final native unrelated sequence closure',()=>{
 it('rejects any persistent counter outside the two approved identities',()=>{const a=row(),b=row(),counter={lastValue:'10',isCalled:true,increment:'1',cache:'1',cycle:false};a.snapshot.sequences['public.workflow_node_events_id_seq']={...counter};b.snapshot.sequences['public.workflow_node_events_id_seq']={...counter,lastValue:'11'};expect(()=>implemented().assertWorkflowNativePostflight(a,b,'total')).toThrow('UNAPPROVED_SEQUENCE_CHANGE')})
})

describe('lossless compact native snapshot serialization',()=>{
 it('exports the complete result as JSON text without pruning any catalogue metadata',()=>{expect(implemented().workflowNativeSnapshotSql).toContain("pg_catalog.current_setting('taskovia.workflow_snapshot_result')::jsonb::text as snapshot");expect(implemented().workflowNativeSnapshotSql).toContain("'catalogueObjects',objects");expect(implemented().workflowNativeSnapshotSql).toContain("'catalogueObjectCount',object_count");expect(implemented().workflowNativeSnapshotSql).toContain("'catalogueObjectHashesSha256',object_hashes")})
})

function dependencyRow(){
 const r=row(),metadata={classid:1259,objid:16710,objsubid:0,refclassid:1259,refobjid:16499,refobjsubid:9,deptype:'a'}
 const dependency={kind:'dependency',identity:'1259:16710:0:1259:16499:9:a',sha256:workflowSha(JSON.stringify(metadata)),metadata}
 r.snapshot.catalogueObjects.push(dependency as unknown as typeof r.snapshot.catalogueObjects[number],structuredClone(dependency) as unknown as typeof r.snapshot.catalogueObjects[number])
 return reseal(r)
}
describe('lossless dependency catalogue multiset',()=>{
 it('accepts complete repeated dependency rows without pruning their multiplicity',()=>{const a=dependencyRow();expect(implemented().assertWorkflowNativeSnapshot(a)).toBe(a);expect(a.snapshot.catalogueObjectCount).toBe(4);expect(implemented().assertWorkflowNativeCatalogue(a,structuredClone(a))).toBeNull()})
 it('compares repeated rows deterministically across array ordering',()=>{const a=dependencyRow(),b=structuredClone(a);b.snapshot.catalogueObjects.reverse();reseal(b);expect(implemented().assertWorkflowNativeCatalogue(a,b)).toBeNull()})
 it.each(['added','removed'])('rejects %s dependency occurrence even with resealed count and hash-list',(change)=>{const a=dependencyRow(),b=structuredClone(a);if(change==='added')b.snapshot.catalogueObjects.push(structuredClone(b.snapshot.catalogueObjects[2]!));else b.snapshot.catalogueObjects.pop();reseal(b);expect(()=>implemented().assertWorkflowNativeCatalogue(a,b)).toThrow('POSTFLIGHT_DRIFT')})
 it('rejects a modified duplicate body even while the other identical occurrence remains',()=>{const a=dependencyRow(),b=structuredClone(a);b.snapshot.catalogueObjects[2]!.sha256='f'.repeat(64);reseal(b);expect(()=>implemented().assertWorkflowNativeCatalogue(a,b)).toThrow('POSTFLIGHT_DRIFT')})
 it('rejects dependency attribute changes with recalculated full identity and digest',()=>{const a=dependencyRow(),b=structuredClone(a),o=b.snapshot.catalogueObjects[2]!;const metadata=o.metadata as unknown as Record<string,unknown>;metadata.refobjsubid=10;o.identity='1259:16710:0:1259:16499:10:a';o.sha256=workflowSha(JSON.stringify(metadata));reseal(b);expect(()=>implemented().assertWorkflowNativeCatalogue(a,b)).toThrow('POSTFLIGHT_DRIFT')})
 it('continues rejecting repeated OID-backed objects even with resealed count and digest',()=>{const a=dependencyRow();a.snapshot.catalogueObjects.push(structuredClone(a.snapshot.catalogueObjects[1]!));reseal(a);expect(()=>implemented().assertWorkflowNativeSnapshot(a)).toThrow('API_SNAPSHOT_INVALID')})
 it('retains the expiry-only role exception while preserving every dependency occurrence',()=>{const a=dependencyRow(),b=dependencyRow();b.snapshot.catalogueObjects[0]!.metadata.rolvaliduntil='2026-10-05T13:05:00.123456Z';b.snapshot.catalogueObjects[0]!.sha256=workflowSha('new-expiry');b.snapshot.catalogueSha256=workflowSha('new-catalogue');reseal(b);expect(implemented().assertWorkflowNativeCatalogue(a,b)?.field).toBe('rolvaliduntil');expect(b.snapshot.catalogueObjectCount).toBe(4)})
})

describe('fresh admission clock with exact transaction state',()=>{
 it('reuses only the untouched complete snapshot collection body inside the existing transaction',()=>{const n=implemented(),sql=n.workflowNativeAdmissionStateSql(row());expect(n.workflowNativeSnapshotSql).toContain(n.workflowNativeStateCollectionSql);expect(sql).toContain(n.workflowNativeStateCollectionSql);expect(sql).not.toMatch(/begin isolation|begin read only|rollback\s*;|commit\s*;/i);expect(sql).toContain("state->'tables' is distinct from expected->'tables'");expect(sql).toContain("state->'sequences' is distinct from expected->'sequences'");expect(sql).toContain('catalogueComparableSha256');expect(sql).toContain('catalogueObjectCount');expect(sql).toContain('nonRoleObjectHashesSha256');expect(sql).toContain("(cli->'metadata')-'rolvaliduntil'::text");expect(sql).toContain("(expected->'cliMetadata')-'rolvaliduntil'::text");expect(sql).toContain('isfinite(new_expiry)');expect(sql).toContain('new_expiry<old_expiry');expect(sql).toContain("interval '300 seconds'");expect(sql).toContain('WORKFLOW_REHEARSAL_ADMISSION_STATE_CHANGED')})
 it('accepts a later small clock with the same exact database and session identity',()=>{const before=row(),response={rows:[{server_time:'2026-10-05T13:00:20.123456Z',database:'postgres',username:'cli_login_postgres'}]};expect(implemented().workflowNativeAdmissionClock(response,before)).toEqual({serverTime:response.rows[0]!.server_time,database:'postgres',username:'cli_login_postgres'})})
 it.each(['database','username','server_time'])('rejects an unrelated or regressed admission clock field %s',(field)=>{const response={rows:[{server_time:'2026-10-05T12:59:59Z',database:'postgres',username:'cli_login_postgres'}]};if(field==='database'){response.rows[0]!.server_time=time;response.rows[0]!.database='other'}if(field==='username'){response.rows[0]!.server_time=time;response.rows[0]!.username='other'}expect(()=>implemented().workflowNativeAdmissionClock(response,row())).toThrow('ADMISSION_CLOCK')})
})
