import {describe,it,expect,beforeAll} from 'vitest'
import {isDeepStrictEqual} from 'node:util'
import {workflowSha} from '../../../scripts/c1-cost-workflow-rehearsal-inventory.mjs'
let p:typeof import('../../../scripts/c1-cost-workflow-rehearsal-pgtap.mjs')
beforeAll(async()=>{p=await import('../../../scripts/c1-cost-workflow-rehearsal-pgtap.mjs')})
const attributes={rolsuper:true,rolinherit:true,rolcreaterole:true,rolcreatedb:true,rolcanlogin:true,rolreplication:true,rolbypassrls:true,rolconnlimit:-1,rolvaliduntil:null}
const expected={extension:'pgtap',version:'1.3.3',schema:'extensions',owner:'supabase_admin',ownerOid:'10',ownerAttributes:attributes,planMember:true}
function metadata(){return {schemaVersion:2,phase:'installed',expected,actual:{version:'1.3.3',schemaOid:'16392',schema:'extensions',ownerOid:'10',owner:'supabase_admin',ownerAttributes:attributes},caller:{currentUser:'postgres',sessionUser:'postgres',currentUserSuperuser:false},defaultVersion:'1.3.3',planMember:true}}
describe('exact managed pgTAP owner only',()=>{
 it('pins one verified managed owner identity and every safe captured role attribute',()=>{expect(p.workflowPgTapOwnerPolicy).toEqual({oid:'10',name:'supabase_admin',attributes});expect(p.workflowPgTapExpectedMetadata).toEqual(expected);expect(p.workflowPgTapSetup.role).toBe('postgres');expect(p.workflowPgTapSetup.superuser).toBe(false)})
 it('accepts the exact verified installed tuple without any ownership mutation',()=>{expect(p.assertWorkflowPgTapInstalledMetadata).toBeTypeOf('function');expect(()=>p.assertWorkflowPgTapInstalledMetadata(metadata())).not.toThrow();expect(p.workflowPgTapSetupSql).not.toMatch(/alter[\s\S]*owner|grant|revoke|set role/i)})
 it.each([['postgres','16388'],['supabase_admin','11'],['supabase_privileged_role','17486'],['another_superuser','10']])('rejects owner %s OID %s even if it has matching privileged attributes',(owner,ownerOid)=>{expect(p.assertWorkflowPgTapInstalledMetadata).toBeTypeOf('function');const v=metadata();v.actual={...v.actual,owner,ownerOid};expect(()=>p.assertWorkflowPgTapInstalledMetadata(v)).toThrow('PGTAP_INSTALLED_VERSION')})
 it.each(Object.keys(attributes))('rejects drift in pinned attribute %s',key=>{expect(p.assertWorkflowPgTapInstalledMetadata).toBeTypeOf('function');const v=metadata();v.actual={...v.actual,ownerAttributes:{...attributes,[key]:key==='rolconnlimit'?0:key==='rolvaliduntil'?'2030-01-01T00:00:00Z':false}};expect(()=>p.assertWorkflowPgTapInstalledMetadata(v)).toThrow('PGTAP_INSTALLED_VERSION')})
 it.each(['version','schema'] as const)('still rejects mismatched %s',key=>{expect(p.assertWorkflowPgTapInstalledMetadata).toBeTypeOf('function');const v=metadata();v.actual={...v.actual,[key]:'wrong'};expect(()=>p.assertWorkflowPgTapInstalledMetadata(v)).toThrow('PGTAP_INSTALLED_VERSION')})
 it('binds the same exact owner profile into installed SQL and safe expected diagnostics',()=>{const sql=p.workflowPgTapGuardSql('installed');expect(sql).toContain("e.extowner='10'::oid");expect(sql).toContain("owner_role.rolname='supabase_admin'");for(const key of Object.keys(attributes))expect(sql).toContain('owner_role.'+key);expect(sql).not.toContain("pg_get_userbyid(e.extowner)='postgres'");expect(p.workflowPgTapMetadataSql).toContain("'ownerAttributes'");expect(p.workflowPgTapMetadataSql).toContain("'schemaVersion',2");expect(p.workflowPgTapMetadataSql).not.toMatch(/rolpassword|rolconfig|pg_authid/);expect(sql.indexOf('WORKFLOW_REHEARSAL_PGTAP_METADATA')).toBeLessThan(sql.indexOf('WORKFLOW_REHEARSAL_PGTAP_INSTALLED_VERSION'))})
 it('keeps the available privilege, namespace ownership, ACL and controls guard byte-for-byte',async()=>{const {readFileSync}=await import('node:fs');const old=readFileSync('.superpowers/sdd/2026-10-04-document-backed-installment-approval/owner-policy-prechange/scripts-c1-cost-workflow-rehearsal-pgtap.mjs','utf8');const start=old.indexOf(' return String.raw'+String.fromCharCode(96),old.indexOf('export function workflowPgTapGuardSql'));const end=old.indexOf(String.fromCharCode(96)+'\n}',start);const oldGuard=old.slice(start+(' return String.raw'+String.fromCharCode(96)).length,end);expect(isDeepStrictEqual(p.workflowPgTapGuardSql('available'),oldGuard)).toBe(true);expect(workflowSha(p.workflowPgTapGuardSql('available'))).toMatch(/^[a-f0-9]{64}$/)})
})
