import {workflowPgTapExpectedMetadata,workflowPgTapOwnerPolicy} from '../../../scripts/c1-cost-workflow-rehearsal-pgtap.mjs'
import {beforeAll,describe,expect,it,vi} from 'vitest'
import {readFileSync,mkdtempSync,rmSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {tmpdir} from 'node:os'
import {pathToFileURL} from 'node:url'
import {workflowNativeSnapshotSql,workflowAdmissionClockSql} from '../../../scripts/c1-cost-workflow-rehearsal-native.mjs'
import {workflowCliFailure} from '../../../scripts/c1-cost-workflow-rehearsal-transport.mjs'
import {workflowSha} from '../../../scripts/c1-cost-workflow-rehearsal-inventory.mjs'
let implementation:typeof import('../../../scripts/run-c1-pgtap-rollback-diagnostic.mjs')|undefined
beforeAll(async()=>{try{implementation=await import(pathToFileURL(resolve(process.cwd(),'scripts/run-c1-pgtap-rollback-diagnostic.mjs')).href)}catch(error){if(!(error instanceof Error)||!('code' in error)||error.code!=='ERR_MODULE_NOT_FOUND')throw error}})
const implemented=()=>{expect(implementation,'pgTAP-only runner is missing').toBeDefined();return implementation!}
const anchorPath='.superpowers/sdd/2026-10-04-document-backed-installment-approval/native-4e86b2c7-f7ad-4636-83fd-d08fd966dc07-snapshot-2.json'
function anchor(){const row=JSON.parse(readFileSync(resolve(process.cwd(),anchorPath),'utf8'));row.snapshot=JSON.parse(row.snapshot);return row}
const metadata={schemaVersion:2,phase:'installed',expected:workflowPgTapExpectedMetadata,actual:{version:'1.3.3',schemaOid:'16392',schema:'extensions',ownerOid:'10',owner:'supabase_admin',ownerAttributes:workflowPgTapOwnerPolicy.attributes},caller:{currentUser:'postgres',sessionUser:'postgres',currentUserSuperuser:false},defaultVersion:'1.3.3',planMember:true}
function harness(options:{batchError?:Error;drift?:'table'|'sequence';archiveFailure?:boolean;archiveFailureLabel?:string}={}){
 const initial=anchor(),clock=new Date(Date.parse(initial.server_time)+20000).toISOString(),calls:string[]=[],archive=vi.fn(async(_value:unknown,label:string)=>{if(options.archiveFailure&&label==='diagnostic'||options.archiveFailureLabel===label)throw Error('private-archive-token')})
 let captures=0,batches=0
 const query=vi.fn(async(sql:string)=>{calls.push(sql);if(sql===workflowNativeSnapshotSql){captures++;const r=structuredClone(initial);if(options.drift&&captures===2){if(options.drift==='table')r.snapshot.tables[Object.keys(r.snapshot.tables)[0]!]!.count++;else r.snapshot.sequences[Object.keys(r.snapshot.sequences)[0]!]!.lastValue=String(BigInt(r.snapshot.sequences[Object.keys(r.snapshot.sequences)[0]!]!.lastValue)+1n)}return {rows:[{...r,snapshot:JSON.stringify(r.snapshot)}]}}
  if(sql===implementation?.pgTapDiagnosticAllSequenceSql){const sequences:Record<string,unknown>={};let i=10000;for(const [name,value] of Object.entries(initial.snapshot.sequences)){const [schema,...parts]=name.split('.');sequences[String(++i)]={...(value as object),oid:String(i),schemaOid:'16393',schema,name:parts.join('.'),ownerOid:'16388',persistence:'p',aclSha256:'a'.repeat(64),typeOid:'20',start:'1',min:'1',max:'9223372036854775807'}}sequences['99999']={oid:'99999',schemaOid:'16393',schema:'extensions',name:'synthetic_sequence',ownerOid:'16388',persistence:'p',aclSha256:'a'.repeat(64),typeOid:'20',start:'1',increment:'1',min:'1',max:'9223372036854775807',cache:'1',cycle:false,lastValue:'1',isCalled:false};return {rows:[{sequences:JSON.stringify(sequences),server_time:initial.server_time,database:'postgres',username:'postgres'}]}}
  if(sql===workflowAdmissionClockSql)return {rows:[{server_time:clock,database:'postgres',username:'postgres'}]}
  if(sql.startsWith('/*c1cw-')){batches++;if(options.batchError)throw options.batchError;return {rows:[{result:'WORKFLOW_PGTAP_DIAGNOSTIC_GUARD_ACCEPTED',metadata:JSON.stringify(metadata)}]}}
  if(sql.includes('pg_stat_activity'))return {rows:[{server_time:new Date(Date.parse(clock)+11000).toISOString(),backends:[]}]}
  return {rows:[]}
 })
 const lease={assertHeld:vi.fn(),release:vi.fn()},reserve=vi.fn(),assertTarget=vi.fn()
 return {query,calls,archive,lease,reserve,assertTarget,batches:()=>batches,captures:()=>captures}
}
async function execute(h:ReturnType<typeof harness>,extra:Record<string,unknown>={}){
 const n=implemented(),manifest=n.reviewPgTapDiagnostic({cwd:process.cwd()})
 return n.runPgTapDiagnostic({cwd:process.cwd(),execute:true,confirmation:manifest.manifestSha256,env:{TASKOVIA_PGTAP_DIAGNOSTIC_APPROVAL:manifest.manifestSha256},query:h.query,acquireLock:async()=>h.lease,archive:h.archive,reserve:h.reserve,assertTarget:h.assertTarget,...extra})
}
describe('one bounded pgTAP-only diagnostic',()=>{
 it('previews a complete frozen manifest without querying or acquiring a lock',async()=>{const h=harness(),result=await implemented().runPgTapDiagnostic({cwd:process.cwd(),query:h.query,acquireLock:async()=>h.lease,assertTarget:h.assertTarget});expect(result.mode).toBe('preview');expect(result.migrations).toEqual([]);expect(result.fixtures).toEqual([]);expect(result.assertions).toBe(0);expect(result.sequenceAllocationsAllowed).toBe(0);expect(result.timeouts.transactionSeconds).toBe(150);expect(result.timeouts.admissionSeconds).toBe(10);expect(h.query).not.toHaveBeenCalled();expect(h.assertTarget).not.toHaveBeenCalled();expect(h.lease.release).not.toHaveBeenCalled()})
 it('rejects missing execution approval before target/network/lock activity',async()=>{const h=harness();await expect(implemented().runPgTapDiagnostic({execute:true,cwd:process.cwd(),query:h.query,acquireLock:async()=>h.lease,assertTarget:h.assertTarget,env:{}})).rejects.toThrow('AUTHORIZATION_REQUIRED');expect(h.query).not.toHaveBeenCalled();expect(h.assertTarget).not.toHaveBeenCalled()})
 it('dispatches one pgTAP CREATE after the tiny clock with complete state check and no cost payload',async()=>{const h=harness(),result=await execute(h);expect(result.mode).toBe('executed');expect(result.actualAssertions).toBe(0);expect(h.batches()).toBe(1);expect(result.sequenceAllocations).toEqual(['0','0']);expect(h.reserve).toHaveBeenCalledTimes(1);const sql=h.calls.find(s=>s.startsWith('/*c1cw-'))!;expect((sql.match(/create extension pgtap/g)||[])).toHaveLength(1);expect(implemented().pgTapDiagnosticPayloadSql).not.toMatch(/create temporary table|create table public\.cost_|c1f5[0-9a-f]{4}-|20261004210[0-7]00/);expect(sql).toContain('WORKFLOW_REHEARSAL_ADMISSION_STATE_CHANGED');expect(sql.indexOf('do $workflow_snapshot$')).toBeLessThan(sql.indexOf('create extension pgtap'));expect(sql).toContain('WORKFLOW_REHEARSAL_PGTAP_METADATA');expect(sql).toContain('WORKFLOW_REHEARSAL_PGTAP_INSTALLED_VERSION');expect(sql).toContain('log_min_messages');const i=h.calls.indexOf(workflowAdmissionClockSql);expect(h.calls[i+1]).toBe(sql);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('retains diagnostics and recovery correlation, then cleans up and postflights failed installed guards',async()=>{const error=workflowCliFailure({category:'COMMAND',status:1,stdout:JSON.stringify({message:'ERROR: P0001: WORKFLOW_REHEARSAL_PGTAP_INSTALLED_VERSION'}),stderr:'',sqlSha256:'a'.repeat(64)}),h=harness({batchError:error});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');expect(h.batches()).toBe(1);expect(h.captures()).toBe(2);expect(h.archive.mock.calls.some(([,l])=>l==='diagnostic')).toBe(true);expect(h.archive.mock.calls.some(([,l])=>l==='recovery-index')).toBe(true);expect(h.archive.mock.calls.some(([,l])=>l==='closure')).toBe(true);expect(h.calls.some(s=>s.includes('pg_stat_activity'))).toBe(true);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('still cleans up and postflights when diagnostic archival fails',async()=>{const h=harness({batchError:workflowCliFailure({category:'COMMAND',status:1,stdout:'ERROR: P0001: WORKFLOW_REHEARSAL_PGTAP_INSTALLED_VERSION',stderr:'',sqlSha256:'b'.repeat(64)}),archiveFailure:true});const error=await execute(h).catch(e=>e);expect(error.message).toContain('WORKFLOW_REHEARSAL_');expect(error.message).not.toContain('private-archive-token');expect(h.captures()).toBe(2);expect(h.calls.some(s=>s.includes('pg_stat_activity'))).toBe(true);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('validates complete postflight state even if storing the after snapshot fails',async()=>{const h=harness({archiveFailureLabel:'snapshot-after'});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');const saved=h.archive.mock.calls.find(([,label])=>label==='closure')?.[0] as {closure?:{everySequenceUnchanged:boolean}};expect(saved?.closure?.everySequenceUnchanged).toBe(true);expect(h.captures()).toBe(2);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('detects sequence drift even if the after-snapshot archive cannot be written',async()=>{const h=harness({drift:'sequence',archiveFailureLabel:'snapshot-after'});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');const saved=h.archive.mock.calls.find(([,label])=>label==='closure')?.[0] as {postflightFailure?:string};expect(saved?.postflightFailure).toBe('WORKFLOW_REHEARSAL_PGTAP_DIAGNOSTIC_SEQUENCE_CHANGED')})
 it.each(['table','sequence'] as const)('rejects any %s postflight change with zero allowance',async(drift)=>{const h=harness({drift});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');expect(h.batches()).toBe(1);expect(h.captures()).toBe(2);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('checks sequence counters in schemas outside the historical five-schema snapshot',async()=>{const h=harness(),result=await execute(h);expect(result.closure.everySequenceUnchanged).toBe(true);const n=implemented();expect(n.pgTapDiagnosticAllSequenceSql).toContain('join pg_catalog.pg_sequence');expect(n.pgTapDiagnosticAllSequenceSql).not.toMatch(/nspname in/);expect(h.calls.filter(s=>s===n.pgTapDiagnosticAllSequenceSql)).toHaveLength(2);const sql=h.calls.find(s=>s.startsWith('/*c1cw-'))!;expect(sql).toContain('WORKFLOW_REHEARSAL_PGTAP_ALL_SEQUENCE_CHANGED');expect(sql.indexOf('WORKFLOW_REHEARSAL_PGTAP_ALL_SEQUENCE_CHANGED')).toBeLessThan(sql.indexOf('create extension pgtap'))})
 it('rejects drift in an extensions sequence omitted from the historical snapshot',async()=>{const h=harness(),n=implemented(),original=h.query;let count=0;h.query=vi.fn(async(sql:string)=>{const result=await original(sql);if(sql===n.pgTapDiagnosticAllSequenceSql){count++;if(count===2){const row=result.rows[0] as Record<string,unknown>,seq=JSON.parse(row.sequences as string);seq['99999'].lastValue='2';row.sequences=JSON.stringify(seq)}}return result});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');const saved=h.archive.mock.calls.find(([,label])=>label==='closure')?.[0] as {postflightFailure?:string};expect(saved?.postflightFailure).toBe('WORKFLOW_REHEARSAL_PGTAP_ALL_SEQUENCE_CHANGED');expect(h.batches()).toBe(1)})
 it('rejects fresh baseline drift before reserving or sending a mutation batch',async()=>{const h=harness(),original=h.query;h.query=vi.fn(async(sql:string)=>{const r=await original(sql);if(sql===workflowNativeSnapshotSql){const row=r.rows[0] as Record<string,unknown>,s=JSON.parse(row.snapshot as string);s.tables[Object.keys(s.tables)[0]].count++;row.snapshot=JSON.stringify(s)}return r});await expect(execute(h)).rejects.toThrow('WORKFLOW_REHEARSAL_');expect(h.reserve).not.toHaveBeenCalled();expect(h.batches()).toBe(0)})
 it('a consumed reservation cannot dispatch another mutation',async()=>{const h=harness();h.reserve.mockImplementation(()=>{throw Error('WORKFLOW_REHEARSAL_RETRY_ALREADY_CONSUMED')});await expect(execute(h)).rejects.toThrow('RETRY_ALREADY_CONSUMED');expect(h.batches()).toBe(0);expect(h.lease.release).toHaveBeenCalledTimes(1)})
 it('atomically consumes the exact manifest once and preserves other markers',()=>{const n=implemented(),dir=mkdtempSync(join(tmpdir(),'pgtap-only-'));try{n.reservePgTapDiagnostic(dir,'a'.repeat(64),{baselineSha256:'b'.repeat(64),runId:'first'});expect(()=>n.reservePgTapDiagnostic(dir,'a'.repeat(64),{baselineSha256:'c'.repeat(64),runId:'second'})).toThrow('RETRY_ALREADY_CONSUMED');expect(JSON.parse(readFileSync(join(dir,'pgtap-diagnostic-'+ 'a'.repeat(64)+'.started.json'),'utf8')).baselineSha256).toBe('b'.repeat(64))}finally{rmSync(dir,{recursive:true,force:true})}})
 it('rejects unsafe/unexpected metadata fields while accepting the fixed safe contract',()=>{const n=implemented();expect(n.parsePgTapDiagnosticMetadata(JSON.stringify(metadata))).toEqual(metadata);expect(()=>n.parsePgTapDiagnosticMetadata(JSON.stringify({...metadata,password:'private'}))).toThrow('METADATA_INVALID');expect(()=>n.parsePgTapDiagnosticMetadata(JSON.stringify({...metadata,actual:{...metadata.actual,owner:'private-token'}}))).toThrow('METADATA_INVALID');expect(()=>n.parsePgTapDiagnosticMetadata('x'.repeat(2049))).toThrow('METADATA_INVALID')})
 it('binds the complete retained anchor and every execution source to the manifest',()=>{const m=implemented().reviewPgTapDiagnostic({cwd:process.cwd()});expect(m.anchor.file).toBe(anchorPath);expect(m.anchor.sha256).toBe(workflowSha(readFileSync(resolve(process.cwd(),anchorPath))));expect(m.executionSources.some((s:{name:string})=>s.name==='scripts/run-c1-pgtap-rollback-diagnostic.mjs')).toBe(true);expect(m.metadataEvidence.serverSeverity).toBe('WARNING');expect(m.metadataEvidence.requiredLogThreshold).toBe('warning-or-lower')})
})
