import { z } from 'zod'
import { recordSubcontractPaymentResultSchema,voidSubcontractPaymentResultSchema,type RecordSubcontractPaymentInput,type VoidSubcontractPaymentInput } from '../../../../shared/schemas/costs/project-finance-writes'
import { AppApiError } from '../../../utils/api-error'
import type { UserSupabaseClient } from '../../../utils/supabase-client'
type Result={data:unknown;error:unknown}; interface Client{rpc(name:'c1_record_subcontract_payment'|'c1_void_subcontract_payment',args:Record<string,unknown>):Promise<Result>}
export interface ProjectFinanceWriteContext{companyId:string;requestId:string}
function fail():never{throw new AppApiError(500,'INTERNAL_ERROR','Không thể ghi nhận thanh toán.')}
function rpcError(error:unknown):never{const parsed=z.object({code:z.string().optional(),message:z.string().optional()}).safeParse(error);const code=parsed.success?parsed.data.message??parsed.data.code:undefined;if(code==='PERMISSION_DENIED')throw new AppApiError(403,'PERMISSION_DENIED','Bạn không có quyền thực hiện thao tác này.');if(code==='RESOURCE_NOT_FOUND')throw new AppApiError(404,'RESOURCE_NOT_FOUND','Không tìm thấy thanh toán hoặc hợp đồng thầu phụ.');if(code==='VERSION_CONFLICT'||code==='IDEMPOTENCY_CONFLICT'||code==='PAYMENT_ALREADY_VOIDED')throw new AppApiError(409,code,'Dữ liệu thanh toán đã thay đổi.');if(code==='HISTORY_IMMUTABLE'||code==='C1_FINANCE_POSTED_MONEY_IMMUTABLE')throw new AppApiError(409,'HISTORY_IMMUTABLE','Số tiền đã ghi nhận là bất biến.');if(code==='INPUT_INVALID')throw new AppApiError(400,'INPUT_INVALID','Dữ liệu không hợp lệ.');return fail()}
export class ProjectFinanceWriteRepository{private readonly client:Client;constructor(client:UserSupabaseClient){this.client=client as unknown as Client}async recordPayment(context:ProjectFinanceWriteContext,projectId:string,subcontractId:string,input:RecordSubcontractPaymentInput,idempotencyKey:string){const response=await this.client.rpc('c1_record_subcontract_payment',{target_company_id:context.companyId,target_project_id:projectId,target_subcontract_id:subcontractId,target_input:input,target_idempotency_key:idempotencyKey,target_request_id:context.requestId});if(response.error)return rpcError(response.error);const result=recordSubcontractPaymentResultSchema.safeParse(response.data);return result.success?result.data:fail()}async voidPayment(context:ProjectFinanceWriteContext,projectId:string,subcontractId:string,paymentId:string,input:VoidSubcontractPaymentInput,idempotencyKey:string){const response=await this.client.rpc('c1_void_subcontract_payment',{target_company_id:context.companyId,target_project_id:projectId,target_subcontract_id:subcontractId,target_payment_id:paymentId,target_expected_version:input.expectedVersion,target_reason:input.reason,target_idempotency_key:idempotencyKey,target_request_id:context.requestId});if(response.error)return rpcError(response.error);const result=voidSubcontractPaymentResultSchema.safeParse(response.data);return result.success?result.data:fail()}}
