import type { H3Event } from 'h3'
import { getRouterParam, readBody } from 'h3'
import { z } from 'zod'
import { createEngagementComponentInputSchema, createEngagementInputSchema, updateEngagementComponentInputSchema, updateEngagementInputSchema } from '../../../shared/schemas/costs/master-data'
import { AppApiError } from '../../utils/api-error'
import { c1RequestContext } from '../c1-master-data/context'
import { createSupabaseEngagementRepository } from './engagement.repository'
import { createEngagementService } from './engagement.service'
const uuid = z.string().uuid()
function param(event: H3Event, name: string) { const value = uuid.safeParse(getRouterParam(event, name)); if (!value.success) throw new AppApiError(400, 'COMPANY_CONTEXT_REQUIRED', 'Định danh không hợp lệ.'); return value.data }
async function input(event: H3Event, schema: typeof createEngagementInputSchema | typeof updateEngagementInputSchema | typeof createEngagementComponentInputSchema | typeof updateEngagementComponentInputSchema) { const value = schema.safeParse(await readBody(event)); if (!value.success) throw new AppApiError(400, 'COMPANY_CONTEXT_REQUIRED', 'Dữ liệu yêu cầu không hợp lệ.'); return value.data }
export function createSupabaseEngagementRoutes(event: H3Event) { async function service() { const companyId = param(event, 'companyId'); const context = await c1RequestContext(event, companyId); return { context, service: createEngagementService(createSupabaseEngagementRepository(context.db)) } } return { async list() { const value = await service(); return value.service.list(value.context, param(event, 'projectId')) }, async get() { const value = await service(); return value.service.get(value.context, param(event, 'projectId'), param(event, 'engagementId')) }, async create() { const value = await service(); return value.service.create(value.context, param(event, 'projectId'), await input(event, createEngagementInputSchema) as never) }, async update() { const value = await service(); return value.service.update(value.context, param(event, 'projectId'), param(event, 'engagementId'), await input(event, updateEngagementInputSchema) as never) }, async listComponents() { const value = await service(); return value.service.listComponents(value.context, param(event, 'engagementId')) }, async getComponent() { const value = await service(); return value.service.getComponent(value.context, param(event, 'engagementId'), param(event, 'componentId')) }, async createComponent() { const value = await service(); return value.service.createComponent(value.context, param(event, 'engagementId'), await input(event, createEngagementComponentInputSchema) as never) }, async updateComponent() { const value = await service(); return value.service.updateComponent(value.context, param(event, 'engagementId'), param(event, 'componentId'), await input(event, updateEngagementComponentInputSchema) as never) } } }
