import { z } from 'zod'
import { businessPartySchema, type BusinessParty, type CreateBusinessPartyInput, type UpdateBusinessPartyInput } from '../../../shared/schemas/costs/master-data'
import { AppApiError } from '../../utils/api-error'
import type { UserSupabaseClient } from '../../utils/supabase-client'
const row = z.object({ id: z.string().uuid(), tenant_id: z.string().uuid(), company_id: z.string().uuid(), code: z.string(), display_name: z.string(), party_kind: z.enum(['crew', 'organization']), tax_identifier: z.string().nullable(), contact_display_name: z.string().nullable(), contact_phone: z.string().nullable(), is_active: z.boolean(), version: z.number().int().nonnegative(), created_at: z.string().datetime(), updated_at: z.string().datetime() }).strict()
interface Query { select(columns: string): Query; eq(column: string, value: string): Query; order(column: string): PromiseLike<{ data: unknown; error: unknown }>; maybeSingle(): Promise<{ data: unknown; error: unknown }> }
interface Client { from(table: 'business_parties'): Query; rpc(name: 'c1_create_business_party' | 'c1_update_business_party', args: Record<string, unknown>): Promise<{ data: unknown; error: unknown }> }
function fail(message: string): never { throw new AppApiError(500, 'INTERNAL_ERROR', message) }
function map(value: unknown): BusinessParty { const parsed = row.safeParse(value); if (!parsed.success) return fail('Không thể đọc Business Party.'); return businessPartySchema.parse({ id: parsed.data.id, code: parsed.data.code, displayName: parsed.data.display_name, partyKind: parsed.data.party_kind, taxIdentifier: parsed.data.tax_identifier, contactDisplayName: parsed.data.contact_display_name, contactPhone: parsed.data.contact_phone, isActive: parsed.data.is_active, version: parsed.data.version, createdAt: parsed.data.created_at, updatedAt: parsed.data.updated_at }) }
function mapRpc(error: unknown): never { const value = z.object({ code: z.string().optional(), message: z.string().optional() }).safeParse(error); if (value.success && value.data.code === 'P0001' && value.data.message === 'MODULE_DISABLED') throw new AppApiError(403, 'PERMISSION_DENIED', 'C1 chưa được bật cho công ty này.'); if (value.success && value.data.code === 'P0001' && value.data.message === 'VERSION_CONFLICT') throw new AppApiError(409, 'VERSION_CONFLICT', 'Dữ liệu đã thay đổi.'); return fail('Không thể cập nhật Business Party.') }
export interface BusinessPartyDataRepository { list(companyId: string, tenantId: string): Promise<BusinessParty[]>; get(companyId: string, tenantId: string, id: string): Promise<BusinessParty | null>; create(companyId: string, tenantId: string, input: CreateBusinessPartyInput, requestId: string): Promise<BusinessParty>; update(companyId: string, tenantId: string, id: string, input: UpdateBusinessPartyInput, requestId: string): Promise<BusinessParty> }
export function createSupabaseBusinessPartyRepository(db: UserSupabaseClient): BusinessPartyDataRepository { const client = db as unknown as Client; const columns = 'id, tenant_id, company_id, code, display_name, party_kind, tax_identifier, contact_display_name, contact_phone, is_active, version, created_at, updated_at'; async function get(companyId: string, tenantId: string, id: string) { const { data, error } = await client.from('business_parties').select(columns).eq('tenant_id', tenantId).eq('company_id', companyId).eq('id', id).maybeSingle(); if (error) return fail('Không thể đọc Business Party.'); return data === null ? null : map(data) } return { async list(companyId, tenantId) { const { data, error } = await client.from('business_parties').select(columns).eq('tenant_id', tenantId).eq('company_id', companyId).order('created_at'); const parsed = z.array(row).safeParse(data); if (error || !parsed.success) return fail('Không thể đọc Business Party.'); return parsed.data.map(map) }, get, async create(companyId, tenantId, input, requestId) { const { data, error } = await client.rpc('c1_create_business_party', { target_company_id: companyId, target_input: input, target_request_id: requestId }); if (error) return mapRpc(error); const result = z.object({ id: z.string().uuid() }).safeParse(data); if (!result.success) return fail('Không thể tạo Business Party.'); return (await get(companyId, tenantId, result.data.id)) ?? fail('Không thể đọc Business Party.') }, async update(companyId, tenantId, id, input, requestId) { const { error } = await client.rpc('c1_update_business_party', { target_company_id: companyId, target_id: id, target_input: input, target_request_id: requestId }); if (error) return mapRpc(error); return (await get(companyId, tenantId, id)) ?? fail('Không thể đọc Business Party.') } } }
