export type {
  AddContactMethodInput,
  AddOpportunityReferrerInput,
  AddOpportunityScopeInput,
  AppendIntakeRecordInput,
  Contact,
  ContactMethod,
  CorrectIntakeRecordInput,
  CreateContactInput,
  CreateOpportunityInput,
  CreateStage01OpportunityResult,
  DuplicateConcern,
  EndOpportunityContactInput,
  EndOpportunityReferrerInput,
  InvalidateOpportunityInput,
  IntakeRecord,
  LinkOpportunityContactInput,
  OpportunityContact,
  OpportunityDetail,
  OpportunityReferrer,
  OpportunityScope,
  OpportunitySummary,
  RaiseDuplicateConcernInput,
  ResolveDuplicateConcernInput,
  RestoreOpportunityInput,
  RetireOpportunityScopeInput,
  SetPrimaryContactInput,
  SetPrimaryReferrerInput,
  UpdateContactInput,
  UpdateContactMethodInput,
  UpdateOpportunityInput,
} from '../../../shared/schemas/opportunities'
export type { OpportunityCreateOptions } from '../../../shared/schemas/opportunity-create-options'
