create table public.file_objects (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null,
  access_class text not null default 'company_financial' check (access_class = 'company_financial'), storage_provider text not null default 'supabase' check (storage_provider = 'supabase'),
  bucket text not null default 'taskovia-c1-financial', object_key text not null, original_name text not null,
  mime_type text, byte_size bigint check (byte_size is null or byte_size > 0 and byte_size <= 20971520), sha256 text check (sha256 is null or sha256 ~ '^[a-f0-9]{64}$'),
  state text not null default 'pending' check (state in ('pending','ready','rejected','abandoned')),
  preview_state text not null default 'available' check (preview_state in ('available','limited','unsupported','failed')),
  uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now(), finalized_at timestamptz, version bigint not null default 0,
  unique (id, tenant_id, company_id), unique (bucket, object_key), foreign key (company_id, tenant_id) references public.companies(id, tenant_id),
  check ((state = 'ready') = (mime_type is not null and byte_size is not null and sha256 is not null and finalized_at is not null))
);
create table public.accounting_sources (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null, code text not null, title text not null, source_system text not null,
  suggested_project_id uuid, is_archived boolean not null default false, version bigint not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (id, tenant_id, company_id), unique (tenant_id, company_id, code), foreign key (company_id, tenant_id) references public.companies(id, tenant_id),
  foreign key (suggested_project_id, tenant_id, company_id) references public.projects(id, tenant_id, company_id)
);
create table public.accounting_source_versions (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null, source_id uuid not null, version_no integer not null check (version_no > 0), file_id uuid not null,
  source_version_label text, source_period_text text, source_as_of_text text, received_at timestamptz not null default now(), status text not null default 'draft' check (status in ('draft','shared')),
  shared_by uuid references auth.users(id), shared_at timestamptz, version bigint not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
  unique (id, tenant_id, company_id), unique (source_id, version_no), foreign key (source_id, tenant_id, company_id) references public.accounting_sources(id, tenant_id, company_id),
  foreign key (file_id, tenant_id, company_id) references public.file_objects(id, tenant_id, company_id), check ((status = 'shared') = (shared_by is not null and shared_at is not null))
);
create table public.source_selections (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null, source_version_id uuid not null, locator jsonb not null, locator_key text not null,
  source_role text not null check (source_role in ('unknown','detail','subtotal','report_total','duplicate_presentation','supporting')),
  handling text not null check (handling in ('pending','ready_for_normalization','reference_only','excluded')), raw_description text, raw_date_text text,
  date_review_status text not null default 'unknown' check (date_review_status in ('unknown','checked','needs_review')), mapped_project_id uuid, mapped_engagement_id uuid, mapped_component_id uuid, handling_reason text,
  version bigint not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (id, tenant_id, company_id), unique (source_version_id, locator_key), foreign key (source_version_id, tenant_id, company_id) references public.accounting_source_versions(id, tenant_id, company_id),
  foreign key (mapped_project_id, tenant_id, company_id) references public.projects(id, tenant_id, company_id), foreign key (mapped_engagement_id, tenant_id, company_id) references public.project_engagements(id, tenant_id, company_id),
  foreign key (mapped_component_id, tenant_id, company_id) references public.engagement_components(id, tenant_id, company_id),
  check (handling <> 'ready_for_normalization' or (source_role <> 'unknown' and mapped_project_id is not null and mapped_engagement_id is not null)),
  check (handling not in ('reference_only','excluded') or handling_reason is not null)
);
create table public.source_reported_figures (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null, source_selection_id uuid not null, figure_family_id uuid not null, revision_no integer not null check (revision_no > 0), replaces_figure_id uuid,
  label text not null, metric_kind text not null check (metric_kind in ('cost_total','labor_total','commitment_total','cash_total','reported_balance','unclassified')),
  raw_value_text text not null, value_state text not null check (value_state in ('known','blank','formula_error','missing_cached','not_numeric')), amount numeric(20,4), currency_code text,
  basis text not null check (basis in ('net','gross','payable_basis','cash','mixed','unknown')), scope_description text not null, status text not null default 'draft' check (status in ('draft','shared')),
  version bigint not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), shared_by uuid references auth.users(id), shared_at timestamptz,
  unique (id, tenant_id, company_id), unique (figure_family_id, revision_no), foreign key (source_selection_id, tenant_id, company_id) references public.source_selections(id, tenant_id, company_id),
  foreign key (replaces_figure_id, tenant_id, company_id) references public.source_reported_figures(id, tenant_id, company_id), check ((value_state = 'known') = (amount is not null)), check ((status = 'shared') = (shared_by is not null and shared_at is not null))
);
create table public.source_review_issues (
  id uuid primary key, tenant_id uuid not null references public.tenants(id), company_id uuid not null, source_selection_id uuid not null, related_selection_id uuid,
  issue_kind text not null check (issue_kind in ('scope_uncertain','party_uncertain','semantics_uncertain','date_conflict','rounding_difference','formula_error','possible_duplicate','coverage_overlap','other')),
  description text not null, impact text not null check (impact in ('blocks_normalization','comparison_only')), status text not null default 'open' check (status in ('open','resolved')),
  resolution text, resolution_note text, resolution_reference text, version bigint not null default 0, opened_by uuid not null references auth.users(id), opened_at timestamptz not null default now(), resolved_by uuid references auth.users(id), resolved_at timestamptz,
  unique (id, tenant_id, company_id), foreign key (source_selection_id, tenant_id, company_id) references public.source_selections(id, tenant_id, company_id), foreign key (related_selection_id, tenant_id, company_id) references public.source_selections(id, tenant_id, company_id),
  check ((status = 'resolved') = (resolution is not null and resolution_note is not null and resolved_by is not null and resolved_at is not null))
);

create index file_objects_scope_idx on public.file_objects(tenant_id, company_id, state, created_at, id);
create index accounting_sources_scope_idx on public.accounting_sources(tenant_id, company_id, is_archived, created_at, id);
create index accounting_source_versions_source_idx on public.accounting_source_versions(source_id, version_no);
create index source_selections_scope_idx on public.source_selections(tenant_id, company_id, source_version_id, handling, created_at, id);
create index source_figures_scope_idx on public.source_reported_figures(tenant_id, company_id, figure_family_id, revision_no);
create index source_review_issues_scope_idx on public.source_review_issues(tenant_id, company_id, status, opened_at, id);

alter table public.file_objects enable row level security; alter table public.accounting_sources enable row level security; alter table public.accounting_source_versions enable row level security; alter table public.source_selections enable row level security; alter table public.source_reported_figures enable row level security; alter table public.source_review_issues enable row level security;
alter table public.file_objects force row level security; alter table public.accounting_sources force row level security; alter table public.accounting_source_versions force row level security; alter table public.source_selections force row level security; alter table public.source_reported_figures force row level security; alter table public.source_review_issues force row level security;
revoke all on public.file_objects, public.accounting_sources, public.accounting_source_versions, public.source_selections, public.source_reported_figures, public.source_review_issues from public, anon, authenticated;
grant select on public.file_objects, public.accounting_sources, public.accounting_source_versions, public.source_selections, public.source_reported_figures, public.source_review_issues to authenticated;
create policy c1_sources_select on public.accounting_sources for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read'));
create policy c1_source_versions_select on public.accounting_source_versions for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read'));
create policy c1_source_selections_select on public.source_selections for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read'));
create policy c1_source_figures_select on public.source_reported_figures for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read'));
create policy c1_source_issues_select on public.source_review_issues for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read'));
create policy c1_files_select on public.file_objects for select to authenticated using (private.has_company_permission(tenant_id, company_id, 'cost.source.read') and private.has_company_permission(tenant_id, company_id, 'cost.file.read'));

insert into storage.buckets(id, name, public) values ('taskovia-c1-financial','taskovia-c1-financial',false) on conflict (id) do update set public = false;
create policy c1_financial_storage_insert on storage.objects for insert to authenticated with check (bucket_id='taskovia-c1-financial' and exists (select 1 from public.file_objects file where file.bucket=bucket_id and file.object_key=name and file.state='pending' and private.has_company_permission(file.tenant_id,file.company_id,'cost.source.read') and private.has_company_permission(file.tenant_id,file.company_id,'cost.prepare')));
create policy c1_financial_storage_read on storage.objects for select to authenticated using (bucket_id='taskovia-c1-financial' and exists (select 1 from public.file_objects file where file.bucket=bucket_id and file.object_key=name and file.state='ready' and private.has_company_permission(file.tenant_id,file.company_id,'cost.source.read') and private.has_company_permission(file.tenant_id,file.company_id,'cost.file.read')));

create function private.c1_source_context(target_company_id uuid, target_permission text) returns jsonb language sql stable security definer set search_path='' as $$ select private.c1_master_context(target_company_id,target_permission); $$;
create function private.c1_create_accounting_source(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_id uuid:=gen_random_uuid();
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); insert into public.accounting_sources(id,tenant_id,company_id,code,title,source_system,suggested_project_id,created_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,btrim(target_input->>'code'),btrim(target_input->>'title'),btrim(target_input->>'sourceSystem'),nullif(target_input->>'suggestedProjectId','')::uuid,(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'code',target_input->>'code','title',target_input->>'title','sourceSystem',target_input->>'sourceSystem','suggestedProjectId',null,'isArchived',false,'version',0,'createdAt',now(),'updatedAt',now()); end; $$;
create function private.c1_create_accounting_source_version(target_company_id uuid,target_source_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_file_id uuid:=gen_random_uuid(); v_id uuid:=gen_random_uuid(); v_no integer;
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); perform 1 from public.accounting_sources source where source.id=target_source_id and source.tenant_id=(v_context->>'tenantId')::uuid and source.company_id=target_company_id for update; if not found then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; select coalesce(max(version_no),0)+1 into v_no from public.accounting_source_versions where source_id=target_source_id; insert into public.file_objects(id,tenant_id,company_id,bucket,object_key,original_name,uploaded_by) values(v_file_id,(v_context->>'tenantId')::uuid,target_company_id,'taskovia-c1-financial',format('c1-acceptance/%s/%s',target_request_id,v_file_id),btrim(target_input->>'originalName'),(v_context->>'actorId')::uuid); insert into public.accounting_source_versions(id,tenant_id,company_id,source_id,version_no,file_id,source_version_label,source_period_text,source_as_of_text,created_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,target_source_id,v_no,v_file_id,nullif(target_input->>'sourceVersionLabel',''),nullif(target_input->>'sourcePeriodText',''),nullif(target_input->>'sourceAsOfText',''),(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'status','draft','file',jsonb_build_object('state','pending')); end; $$;
create function private.c1_finalize_file_object(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_file public.file_objects%rowtype;
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); select * into v_file from public.file_objects file where file.id=(target_input->>'id')::uuid and file.tenant_id=(v_context->>'tenantId')::uuid and file.company_id=target_company_id for update; if v_file.id is null then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; if v_file.state='ready' then return jsonb_build_object('id',v_file.id,'bucket',v_file.bucket,'objectKey',v_file.object_key,'originalName',v_file.original_name,'state',v_file.state,'previewState',v_file.preview_state,'version',v_file.version,'mimeType',v_file.mime_type,'byteSize',v_file.byte_size,'sha256',v_file.sha256,'finalizedAt',v_file.finalized_at); end if; update public.file_objects set mime_type=target_input->>'mimeType',byte_size=(target_input->>'byteSize')::bigint,sha256=target_input->>'sha256',state='ready',finalized_at=now(),version=version+1 where id=v_file.id returning * into v_file; return jsonb_build_object('id',v_file.id,'bucket',v_file.bucket,'objectKey',v_file.object_key,'originalName',v_file.original_name,'state',v_file.state,'previewState',v_file.preview_state,'version',v_file.version,'mimeType',v_file.mime_type,'byteSize',v_file.byte_size,'sha256',v_file.sha256,'finalizedAt',v_file.finalized_at); end; $$;
create function private.c1_share_accounting_source_version(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_version public.accounting_source_versions%rowtype;
begin v_context:=private.c1_source_context(target_company_id,'cost.publish_import'); select * into v_version from public.accounting_source_versions version where version.id=target_id and version.tenant_id=(v_context->>'tenantId')::uuid and version.company_id=target_company_id for update; if v_version.id is null then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; if not exists(select 1 from public.file_objects file where file.id=v_version.file_id and file.state='ready') then raise exception using errcode='P0001',message='SOURCE_FILE_NOT_READY'; end if; update public.accounting_source_versions set status='shared',shared_by=(v_context->>'actorId')::uuid,shared_at=now(),version=version+1 where id=target_id returning * into v_version; return jsonb_build_object('id',v_version.id,'sourceId',v_version.source_id,'versionNo',v_version.version_no,'fileId',v_version.file_id,'status',v_version.status,'sourceVersionLabel',v_version.source_version_label,'sourcePeriodText',v_version.source_period_text,'sourceAsOfText',v_version.source_as_of_text,'version',v_version.version,'createdAt',v_version.created_at,'sharedAt',v_version.shared_at); end; $$;
create function private.c1_create_source_selection(target_company_id uuid,target_source_version_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_id uuid:=gen_random_uuid();
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); if not exists(select 1 from public.accounting_source_versions version where version.id=target_source_version_id and version.tenant_id=(v_context->>'tenantId')::uuid and version.company_id=target_company_id) then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; insert into public.source_selections(id,tenant_id,company_id,source_version_id,locator,locator_key,source_role,handling,raw_description,raw_date_text,mapped_project_id,mapped_engagement_id,mapped_component_id,handling_reason,created_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,target_source_version_id,target_input->'locator',target_input->>'locatorKey',target_input->>'sourceRole',target_input->>'handling',nullif(target_input->>'rawDescription',''),nullif(target_input->>'rawDateText',''),nullif(target_input->>'mappedProjectId','')::uuid,nullif(target_input->>'mappedEngagementId','')::uuid,nullif(target_input->>'mappedComponentId','')::uuid,nullif(target_input->>'handlingReason',''),(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'sourceVersionId',target_source_version_id,'locator',target_input->'locator','locatorKey',target_input->>'locatorKey','sourceRole',target_input->>'sourceRole','handling',target_input->>'handling','rawDescription',null,'rawDateText',null,'mappedProjectId',null,'mappedEngagementId',null,'mappedComponentId',null,'handlingReason',null,'version',0,'createdAt',now(),'updatedAt',now()); end; $$;
create function public.c1_create_accounting_source(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_accounting_source(target_company_id,target_input,target_request_id); $$;
create function public.c1_create_accounting_source_version(target_company_id uuid,target_source_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_accounting_source_version(target_company_id,target_source_id,target_input,target_request_id); $$;
create function public.c1_finalize_file_object(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_finalize_file_object(target_company_id,target_input,target_request_id); $$;
create function public.c1_share_accounting_source_version(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_share_accounting_source_version(target_company_id,target_id,target_input,target_request_id); $$;
create function public.c1_create_source_selection(target_company_id uuid,target_source_version_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_source_selection(target_company_id,target_source_version_id,target_input,target_request_id); $$;
revoke all on function public.c1_create_accounting_source(uuid,jsonb,uuid), public.c1_create_accounting_source_version(uuid,uuid,jsonb,uuid), public.c1_finalize_file_object(uuid,jsonb,uuid), public.c1_share_accounting_source_version(uuid,uuid,jsonb,uuid), public.c1_create_source_selection(uuid,uuid,jsonb,uuid) from public, anon, authenticated;
grant execute on function public.c1_create_accounting_source(uuid,jsonb,uuid), public.c1_create_accounting_source_version(uuid,uuid,jsonb,uuid), public.c1_finalize_file_object(uuid,jsonb,uuid), public.c1_share_accounting_source_version(uuid,uuid,jsonb,uuid), public.c1_create_source_selection(uuid,uuid,jsonb,uuid) to authenticated;
revoke all on function private.c1_source_context(uuid,text), private.c1_create_accounting_source(uuid,jsonb,uuid), private.c1_create_accounting_source_version(uuid,uuid,jsonb,uuid), private.c1_finalize_file_object(uuid,jsonb,uuid), private.c1_share_accounting_source_version(uuid,uuid,jsonb,uuid), private.c1_create_source_selection(uuid,uuid,jsonb,uuid) from public, anon, authenticated;

create function private.c1_create_file_upload_intent(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_id uuid:=coalesce(nullif(target_input->>'id','')::uuid,gen_random_uuid()); v_key text;
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); v_key:=coalesce(nullif(target_input->>'objectKey',''),format('c1-acceptance/%s/%s',target_request_id,v_id)); insert into public.file_objects(id,tenant_id,company_id,bucket,object_key,original_name,uploaded_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,'taskovia-c1-financial',v_key,btrim(target_input->>'originalName'),(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'bucket','taskovia-c1-financial','objectKey',v_key,'originalName',target_input->>'originalName','state','pending','previewState','available','version',0); end; $$;
create function private.c1_update_accounting_source(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_source public.accounting_sources%rowtype;
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); select * into v_source from public.accounting_sources source where source.id=target_id and source.tenant_id=(v_context->>'tenantId')::uuid and source.company_id=target_company_id for update; if v_source.id is null then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; if v_source.version<>(target_input->>'expectedVersion')::bigint then raise exception using errcode='P0001',message='VERSION_CONFLICT'; end if; update public.accounting_sources set code=coalesce(nullif(btrim(target_input->>'code'),''),code),title=coalesce(nullif(btrim(target_input->>'title'),''),title),source_system=coalesce(nullif(btrim(target_input->>'sourceSystem'),''),source_system),suggested_project_id=coalesce(nullif(target_input->>'suggestedProjectId','')::uuid,suggested_project_id),is_archived=coalesce((target_input->>'isArchived')::boolean,is_archived),version=version+1,updated_at=now() where id=target_id returning * into v_source; return jsonb_build_object('id',v_source.id,'code',v_source.code,'title',v_source.title,'sourceSystem',v_source.source_system,'suggestedProjectId',v_source.suggested_project_id,'isArchived',v_source.is_archived,'version',v_source.version,'createdAt',v_source.created_at,'updatedAt',v_source.updated_at); end; $$;
create function private.c1_create_source_reported_figure(target_company_id uuid,target_source_selection_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_id uuid:=gen_random_uuid();
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); if not exists(select 1 from public.source_selections selection where selection.id=target_source_selection_id and selection.tenant_id=(v_context->>'tenantId')::uuid and selection.company_id=target_company_id) then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; insert into public.source_reported_figures(id,tenant_id,company_id,source_selection_id,figure_family_id,revision_no,label,metric_kind,raw_value_text,value_state,amount,currency_code,basis,scope_description,created_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,target_source_selection_id,v_id,1,btrim(target_input->>'label'),target_input->>'metricKind',target_input->>'rawValueText',target_input->>'valueState',nullif(target_input->>'amount','')::numeric,nullif(target_input->>'currencyCode',''),target_input->>'basis',target_input->>'scopeDescription',(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'sourceSelectionId',target_source_selection_id,'figureFamilyId',v_id,'revisionNo',1,'replacesFigureId',null,'label',target_input->>'label','metricKind',target_input->>'metricKind','rawValueText',target_input->>'rawValueText','valueState',target_input->>'valueState','amount',target_input->'amount','currencyCode',target_input->'currencyCode','basis',target_input->>'basis','scopeDescription',target_input->>'scopeDescription','status','draft','version',0,'createdAt',now(),'sharedAt',null); end; $$;
create function private.c1_share_source_reported_figure(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_figure public.source_reported_figures%rowtype;
begin v_context:=private.c1_source_context(target_company_id,'cost.publish_import'); select * into v_figure from public.source_reported_figures figure where figure.id=target_id and figure.tenant_id=(v_context->>'tenantId')::uuid and figure.company_id=target_company_id for update; if v_figure.id is null then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; if not exists(select 1 from public.source_selections selection join public.accounting_source_versions source_version on source_version.id=selection.source_version_id where selection.id=v_figure.source_selection_id and source_version.status='shared') then raise exception using errcode='P0001',message='SOURCE_VERSION_NOT_SHARED'; end if; update public.source_reported_figures set status='shared',shared_by=(v_context->>'actorId')::uuid,shared_at=now(),version=version+1 where id=target_id returning * into v_figure; return jsonb_build_object('id',v_figure.id,'sourceSelectionId',v_figure.source_selection_id,'figureFamilyId',v_figure.figure_family_id,'revisionNo',v_figure.revision_no,'replacesFigureId',v_figure.replaces_figure_id,'label',v_figure.label,'metricKind',v_figure.metric_kind,'rawValueText',v_figure.raw_value_text,'valueState',v_figure.value_state,'amount',v_figure.amount,'currencyCode',v_figure.currency_code,'basis',v_figure.basis,'scopeDescription',v_figure.scope_description,'status',v_figure.status,'version',v_figure.version,'createdAt',v_figure.created_at,'sharedAt',v_figure.shared_at); end; $$;
create function public.c1_create_file_upload_intent(target_company_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_file_upload_intent(target_company_id,target_input,target_request_id); $$;
create function public.c1_update_accounting_source(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_update_accounting_source(target_company_id,target_id,target_input,target_request_id); $$;
create function public.c1_create_source_reported_figure(target_company_id uuid,target_source_selection_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_source_reported_figure(target_company_id,target_source_selection_id,target_input,target_request_id); $$;
create function public.c1_share_source_reported_figure(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_share_source_reported_figure(target_company_id,target_id,target_input,target_request_id); $$;
revoke all on function public.c1_create_file_upload_intent(uuid,jsonb,uuid), public.c1_update_accounting_source(uuid,uuid,jsonb,uuid), public.c1_create_source_reported_figure(uuid,uuid,jsonb,uuid), public.c1_share_source_reported_figure(uuid,uuid,jsonb,uuid) from public, anon, authenticated;
grant execute on function public.c1_create_file_upload_intent(uuid,jsonb,uuid), public.c1_update_accounting_source(uuid,uuid,jsonb,uuid), public.c1_create_source_reported_figure(uuid,uuid,jsonb,uuid), public.c1_share_source_reported_figure(uuid,uuid,jsonb,uuid) to authenticated;
revoke all on function private.c1_create_file_upload_intent(uuid,jsonb,uuid), private.c1_update_accounting_source(uuid,uuid,jsonb,uuid), private.c1_create_source_reported_figure(uuid,uuid,jsonb,uuid), private.c1_share_source_reported_figure(uuid,uuid,jsonb,uuid) from public, anon, authenticated;

create function private.c1_create_source_review_issue(target_company_id uuid,target_source_selection_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_id uuid:=gen_random_uuid();
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); if not exists(select 1 from public.source_selections selection where selection.id=target_source_selection_id and selection.tenant_id=(v_context->>'tenantId')::uuid and selection.company_id=target_company_id) then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; insert into public.source_review_issues(id,tenant_id,company_id,source_selection_id,related_selection_id,issue_kind,description,impact,opened_by) values(v_id,(v_context->>'tenantId')::uuid,target_company_id,target_source_selection_id,nullif(target_input->>'relatedSelectionId','')::uuid,target_input->>'issueKind',target_input->>'description',target_input->>'impact',(v_context->>'actorId')::uuid); return jsonb_build_object('id',v_id,'status','open','financialActivation',false); end; $$;
create function private.c1_resolve_source_review_issue(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_context jsonb; v_issue public.source_review_issues%rowtype;
begin v_context:=private.c1_source_context(target_company_id,'cost.prepare'); select * into v_issue from public.source_review_issues issue where issue.id=target_id and issue.tenant_id=(v_context->>'tenantId')::uuid and issue.company_id=target_company_id for update; if v_issue.id is null then raise exception using errcode='P0001',message='RESOURCE_NOT_FOUND'; end if; if v_issue.status='resolved' then raise exception using errcode='P0001',message='HISTORY_IMMUTABLE'; end if; if v_issue.version<>(target_input->>'expectedVersion')::bigint then raise exception using errcode='P0001',message='VERSION_CONFLICT'; end if; update public.source_review_issues set status='resolved',resolution=target_input->>'resolution',resolution_note=target_input->>'resolutionNote',resolution_reference=nullif(target_input->>'resolutionReference',''),resolved_by=(v_context->>'actorId')::uuid,resolved_at=now(),version=version+1 where id=target_id returning * into v_issue; return jsonb_build_object('id',v_issue.id,'status',v_issue.status,'financialActivation',false); end; $$;
create function public.c1_create_source_review_issue(target_company_id uuid,target_source_selection_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_create_source_review_issue(target_company_id,target_source_selection_id,target_input,target_request_id); $$;
create function public.c1_resolve_source_review_issue(target_company_id uuid,target_id uuid,target_input jsonb,target_request_id uuid) returns jsonb language sql security definer set search_path='' as $$ select private.c1_resolve_source_review_issue(target_company_id,target_id,target_input,target_request_id); $$;
revoke all on function public.c1_create_source_review_issue(uuid,uuid,jsonb,uuid), public.c1_resolve_source_review_issue(uuid,uuid,jsonb,uuid) from public, anon, authenticated;
grant execute on function public.c1_create_source_review_issue(uuid,uuid,jsonb,uuid), public.c1_resolve_source_review_issue(uuid,uuid,jsonb,uuid) to authenticated;
revoke all on function private.c1_create_source_review_issue(uuid,uuid,jsonb,uuid), private.c1_resolve_source_review_issue(uuid,uuid,jsonb,uuid) from public, anon, authenticated;
